"""INSUFFICIENT_EVIDENCE sub-types IE1-IE4 (assistant-written; see claims.py).

These are the cases where neither side proves anything. The model is meant to say "a human must
look" here, not to guess.
"""

SUBTYPES = {
    "IE1": {  # contradictory statements, no proof
        "claim_family": "NOT_RECEIVED",
        "courier": {"delivered": 0.4, "in_transit": 0.3, "not_dispatched": 0.15, "lost": 0.15},
        "code_used": 0.3,
        "response": [
            "আমি তো পাঠিয়েছি, উনি কেন বলছেন পাননি বুঝতে পারছি না।",
            "আমার কাছে কিছু প্রমাণ নেই, কিন্তু আমি পাঠিয়েছি।",
            "ami pathaisi, ar kichu bolte parbo na.",
            "উনি মনে হয় ভুল বুঝেছেন, আমি আলাদা করে কিছু বলব না।",
            "কুরিয়ারে দিয়েছি কিন্তু রসিদ হারিয়ে ফেলেছি।",
            "আমি বলছি পাঠিয়েছি, উনি বলছেন পাননি।",
            "eta niye kichu bolar nai.",
            "আমি কী প্রমাণ দেব, বলুন।",
            "দুজনের কথা মিলছে না।",
            "আমি পাঠিয়েছি বলেই মনে পড়ে।",
        ],
        "buyer_ev": [
            "",
            "আমি পাইনি, এটাই আমার কথা।",
            "ami paini, ar kichu nai.",
            "",
            "কোনো প্রমাণ নেই।",
            "বাসায় কেউ ছিল না তখন।",
            "",
            "পরিবারের লোকজনকে জিজ্ঞেস করেছি, কেউ জানে না।",
        ],
        "seller_ev": [
            "",
            "",
            "kono proman nai",
            "রসিদ নেই, আছে বলতে পারি না",
            "",
            "",
            "",
            "পাঠানোর কথা মনে আছে",
        ],
    },
    "IE2": {  # change of mind, unclear return policy
        "claim_family": "WANT_REFUND",
        "courier": {"delivered": 1.0},
        "code_used": 0.6,
        "response": [
            "পোস্টে রিটার্ন পলিসি আলাদা করে লেখা ছিল না, আমি নিশ্চিত না।",
            "ফেরত নেওয়ার নিয়ম আমরা পরিষ্কার করে বলিনি, এটা সত্যি।",
            "return policy post e chilo kina ami nije o jani na.",
            "পণ্য ঠিক আছে কিন্তু ফেরত নেব কি না ভাবছি।",
            "",
            "ফেরতযোগ্য কি না এটা স্পষ্ট নয়, আপনারা সিদ্ধান্ত নিন।",
            "return er kotha age bolini, ekhon ki kora jay?",
            "পণ্য অক্ষত কি না জানি না, ফেরত আসেনি।",
            "পলিসি নিয়ে আমাদের দ্বিমত আছে।",
            "ফেরত দেওয়ার সময়সীমা কত ছিল মনে পড়ছে না।",
        ],
        "buyer_ev": [
            "",
            "রিটার্ন পলিসি পোস্টে খুঁজে পাইনি।",
            "ami policy dekhi nai, tai bolchi.",
            "",
            "ফেরতের কথা চ্যাটে হয়েছিল কিন্তু সবটা মনে নেই।",
            "ami chai ferot dite.",
            "",
            "চ্যাটের স্ক্রিনশট আছে কিন্তু কাটা অংশ।",
        ],
        "seller_ev": [
            "",
            "রিটার্ন পলিসি লেখা আছে মনে হয়, লিংক নেই",
            "",
            "policy post er niche chilo kina jani na",
            "",
            "",
            "kono screenshot nai",
            "",
        ],
    },
    "IE3": {  # misunderstanding about the listing
        "claim_family": "NOT_AS_DESCRIBED",
        "courier": {"delivered": 1.0},
        "code_used": 0.5,
        "response": [
            "লিস্টিংয়ে একটা পণ্যের কথাই বলা ছিল, সেট বলিনি।",
            "ছবিতে যা দেখানো ছিল সেটা সাজানোর জন্য ছিল, আলাদা করে লিখিনি।",
            "ami to ekta er dam ei nilam, set e er kotha bolini.",
            "ওনার ভুল বোঝার দায় আমি কীভাবে নেব?",
            "",
            "বর্ণনা অস্পষ্ট ছিল কি না, আমি মানছি হতে পারে।",
            "dui ta o thik, ekta bujhte bhul hoise.",
            "ছবিতে মডেল পরে ছিল, পণ্য শুধু একটাই।",
            "দাম দেখলেই বোঝা যায় এটা একটার দাম।",
            "লিস্টিংয়ে সব বিস্তারিত দেওয়া ছিল না।",
        ],
        "buyer_ev": [
            "লিস্টিংয়ের ছবিতে দুটো দেখা যাচ্ছিল তাই ভেবেছি দুটো পাব।",
            "",
            "post er chobi te ekta set moto lagse.",
            "বর্ণনায় আলাদা করে কিছু লেখা নেই, ছবি দেখে বুঝেছি।",
            "ছবিটি সংরক্ষণ করা নেই, পোস্ট সম্পাদনা করা হয়েছে মনে হচ্ছে।",
            "ami vebechilam eta combo.",
            "",
            "স্ক্রিনশটে দাম দেখা যাচ্ছে না।",
        ],
        "seller_ev": [
            "পোস্টের স্ক্রিনশট কিন্তু ছোট অংশ",
            "",
            "post er link ekhon nai",
            "",
            "",
            "পোস্ট এডিট করা হয়েছিল কি না জানি না",
            "chobi ekta thikthak",
            "",
        ],
    },
    "IE4": {  # evidence exists but is unclear or cut off
        "claim_family": "DAMAGED",
        "courier": {"delivered": 1.0},
        "code_used": 0.5,
        "response": [
            "ছবিতে কিছু বোঝা যাচ্ছে না, আমি কীভাবে মানব?",
            "ভিডিওটা মাঝপথে কেটে গেছে, কী হয়েছে বুঝতে পারিনি।",
            "photo ta blur, ami thik kore dekhte parchi na.",
            "ক্ষতি আছে কি না নিশ্চিত নই।",
            "",
            "আরও পরিষ্কার ছবি পেলে বলতে পারব।",
            "chobi ta dekhe kichu bola jay na.",
            "পণ্য ঠিক ছিল বলেই জানতাম, এখন নিশ্চিত না।",
            "প্রমাণ দেখে আমার সিদ্ধান্ত নেওয়া কঠিন।",
            "আপনারা ছবিটা দেখে বলুন।",
        ],
        "buyer_ev": [
            "ছবি তুলেছি কিন্তু আলো কম, পরিষ্কার নয়।",
            "ভিডিওটা শেষ অংশে কেটে গেছে, সমস্যাটা দেখানোর আগেই।",
            "chobi onek blur, tobu pathalam.",
            "স্ক্রিনশটে তারিখ ও সময় নেই।",
            "পণ্যের একটা অংশ দেখা যাচ্ছে, বাকিটা কাটা।",
            "ফাইল ছোট করতে গিয়ে ছবির মান নষ্ট হয়ে গেছে।",
            "video te kichu bujha jay na.",
            "ছবি দুটো, দুটোই অস্পষ্ট।",
        ],
        "seller_ev": [
            "পাঠানোর আগের ছবি আছে কিন্তু আলো কম",
            "",
            "packing er video ache kintu chhoto",
            "ছবি আছে, তবে অর্ধেক কাটা",
            "",
            "ভিডিওর শুরুটা কেটে গেছে",
            "chobi unclear",
            "",
        ],
    },
}
