/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/analyst/disputes/{dispute_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Case View
         * @description Everything an analyst needs: what happened, why it is risky, and what to do next.
         */
        get: operations["case_view_api_analyst_disputes__dispute_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analyst/disputes/{dispute_id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Decide
         * @description Record the human decision, move the ledger, and refresh the seller's trust score.
         */
        post: operations["decide_api_analyst_disputes__dispute_id__decision_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analyst/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Queue
         * @description Disputes waiting for a human, human-review cases first, larger amounts first.
         */
        get: operations["queue_api_analyst_queue_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/demo/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reset
         * @description Demo only: wipe the database and the simulated clock, then load a scenario set.
         *
         *     The ``demo`` set also creates the seven demo scenarios (BLUEPRINT.md Section 12.2).
         */
        post: operations["reset_api_demo_reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/disputes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Dispute
         * @description The buyer reports a problem. The held money stays in HOLD until an analyst decides.
         */
        post: operations["create_dispute_api_disputes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/disputes/{dispute_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Dispute
         * @description The dispute as both parties see it: claim, evidence, deadline and status.
         *
         *     An addition to the contract. It carries no analysis and no analyst notes; the seller screen
         *     needs it to show the claim and the response deadline.
         */
        get: operations["get_dispute_api_disputes__dispute_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/disputes/{dispute_id}/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyze Dispute
         * @description Run the evidence analyzer. It only suggests; it never moves money.
         */
        post: operations["analyze_dispute_api_disputes__dispute_id__analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/disputes/{dispute_id}/buyer-evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Buyer Evidence
         * @description Extra evidence from the buyer, for example after an analyst asked for more.
         *
         *     An addition to the contract: without it a "request more evidence" decision would give the
         *     buyer no way to answer.
         */
        post: operations["buyer_evidence_api_disputes__dispute_id__buyer_evidence_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/disputes/{dispute_id}/seller-response": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Seller Response */
        post: operations["seller_response_api_disputes__dispute_id__seller_response_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/metrics/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Metrics Summary
         * @description Evaluation numbers exactly as the evaluation scripts wrote them.
         *
         *     ``summary`` is reports/summary.json (Step 12); until it exists the individual reports are
         *     still returned under ``reports``. Nothing is computed here, so a missing number stays missing.
         */
        get: operations["metrics_summary_api_metrics_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Order
         * @description Create a Safe Order and hold the money (simulated). The sandbox code is returned once.
         */
        post: operations["create_order_api_orders_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/{order_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Order */
        get: operations["get_order_api_orders__order_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/{order_id}/confirm-delivery": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm Delivery
         * @description The buyer confirms with the delivery code. A wrong code changes nothing.
         */
        post: operations["confirm_delivery_api_orders__order_id__confirm_delivery_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sellers/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Sellers
         * @description Find sellers by name or wallet number (an addition to the contract, used by the UI).
         */
        get: operations["search_sellers_api_sellers_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sellers/{seller_id}/score-history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Score History */
        get: operations["score_history_api_sellers__seller_id__score_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sim/advance-clock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Advance Clock
         * @description Move the simulated clock forward and fire timers (hold expiry, missed dispatch).
         */
        post: operations["advance_clock_api_sim_advance_clock_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sim/courier-event": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Courier Event */
        post: operations["courier_event_api_sim_courier_event_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trust/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trust Check
         * @description Trust Check for a seller. The first check also stores the INITIAL snapshot.
         */
        post: operations["trust_check_api_trust_check_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdvanceClockRequest */
        AdvanceClockRequest: {
            /** Hours */
            hours: number;
        };
        /** AnalysisOut */
        AnalysisOut: {
            /** Class Probs */
            class_probs: {
                [key: string]: number;
            };
            /** Dispute Id */
            dispute_id: string;
            /** Explanation Bn */
            explanation_bn: string;
            /** Explanation En */
            explanation_en: string;
            /** Explanation Sections */
            explanation_sections: {
                [key: string]: {
                    [key: string]: string;
                };
            };
            /** Flags */
            flags: string[];
            /** Injection Detected */
            injection_detected: boolean;
            /** Model Versions */
            model_versions: {
                [key: string]: string;
            };
            /** Order Id */
            order_id: string;
            /** Recommendation */
            recommendation: string;
            /** Route */
            route: string;
            /** Route Reasons */
            route_reasons: string[];
            /** Timeline */
            timeline: components["schemas"]["TimelineEventOut"][];
        };
        /** AnalystCaseOut */
        AnalystCaseOut: {
            analysis: components["schemas"]["AnalysisOut"] | null;
            buyer: components["schemas"]["BuyerPublic"];
            /** Decisions */
            decisions: components["schemas"]["DecisionRecordOut"][];
            dispute: components["schemas"]["DisputeOut"];
            order: components["schemas"]["OrderOut"];
            seller: components["schemas"]["SellerPublic"];
            seller_trust: components["schemas"]["SnapshotOut"] | null;
        };
        /**
         * AnalystDecisionType
         * @enum {string}
         */
        AnalystDecisionType: "REFUND_BUYER" | "REJECT_CLAIM" | "REQUEST_MORE_EVIDENCE" | "ESCALATE";
        /** BuyerEvidenceRequest */
        BuyerEvidenceRequest: {
            /** Evidence Text */
            evidence_text: string;
        };
        /** BuyerPublic */
        BuyerPublic: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Display Name */
            display_name: string;
            /** Id */
            id: string;
            /** Wallet No */
            wallet_no: string;
        };
        /**
         * ClaimType
         * @enum {string}
         */
        ClaimType: "NOT_RECEIVED" | "WRONG_ITEM" | "DAMAGED" | "NOT_AS_DESCRIBED" | "OTHER";
        /** ClockOut */
        ClockOut: {
            /** Fired */
            fired: components["schemas"]["FiredEvent"][];
            /** Now */
            now: string;
        };
        /** ConfirmDeliveryRequest */
        ConfirmDeliveryRequest: {
            /** Code */
            code: string;
        };
        /** CourierEventRequest */
        CourierEventRequest: {
            /** Order Id */
            order_id: string;
            status: components["schemas"]["CourierStatus"];
        };
        /**
         * CourierStatus
         * @enum {string}
         */
        CourierStatus: "not_dispatched" | "in_transit" | "delivered" | "returned" | "lost";
        /** CreateDisputeRequest */
        CreateDisputeRequest: {
            /** Claim Text */
            claim_text: string;
            claim_type?: components["schemas"]["ClaimType"] | null;
            /**
             * Evidence Text
             * @default
             */
            evidence_text: string;
            /** Order Id */
            order_id: string;
        };
        /** CreateOrderRequest */
        CreateOrderRequest: {
            /** Amount Bdt */
            amount_bdt: number;
            /** Buyer Id */
            buyer_id: string;
            /** Product Category */
            product_category: string;
            /** Seller Id */
            seller_id: string;
        };
        /** DecisionOut */
        DecisionOut: {
            decision: components["schemas"]["AnalystDecisionType"];
            /** Dispute Id */
            dispute_id: string;
            dispute_status: components["schemas"]["DisputeStatus"];
            /** Followed Suggestion */
            followed_suggestion: boolean | null;
            /** Ledger Balanced */
            ledger_balanced: boolean;
            order_status: components["schemas"]["OrderStatus"];
            /** Seller Deadline */
            seller_deadline: string | null;
            trust: components["schemas"]["TrustChange"] | null;
        };
        /** DecisionRecordOut */
        DecisionRecordOut: {
            /** Analyst Id */
            analyst_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            decision: components["schemas"]["AnalystDecisionType"];
            /** Note */
            note: string;
        };
        /** DecisionRequest */
        DecisionRequest: {
            /** Analyst Id */
            analyst_id: string;
            decision: components["schemas"]["AnalystDecisionType"];
            /** Note */
            note: string;
        };
        /** DemoResetOut */
        DemoResetOut: {
            /** Loaded */
            loaded: {
                [key: string]: number;
            };
            /** Now */
            now: string;
            /** Scenario Set */
            scenario_set: string;
            /**
             * Scenarios
             * @default []
             */
            scenarios: components["schemas"]["DemoScenarioOut"][];
        };
        /** DemoResetRequest */
        DemoResetRequest: {
            /**
             * Scenario Set
             * @default default
             */
            scenario_set: string;
        };
        /** DemoScenarioOut */
        DemoScenarioOut: {
            /** Analysis */
            analysis?: string | null;
            /** Buyer Id */
            buyer_id?: string | null;
            /** Delivery Code */
            delivery_code?: string | null;
            /**
             * Detail
             * @default
             */
            detail: string;
            /** Dispute Id */
            dispute_id?: string | null;
            /** Key */
            key: string;
            /** Number */
            number: number;
            /** Order Id */
            order_id?: string | null;
            /** Seller Id */
            seller_id?: string | null;
            /** Seller Name */
            seller_name?: string | null;
        };
        /** DisputeOut */
        DisputeOut: {
            /** Claim Text */
            claim_text: string;
            claim_type: components["schemas"]["ClaimType"] | null;
            /** Evidence */
            evidence: components["schemas"]["EvidenceOut"][];
            /** Id */
            id: string;
            /**
             * Opened At
             * Format: date-time
             */
            opened_at: string;
            opened_by: components["schemas"]["Party"];
            /** Order Id */
            order_id: string;
            /** Seller Deadline */
            seller_deadline: string | null;
            /** Seller Responded At */
            seller_responded_at: string | null;
            /** Seller Response Text */
            seller_response_text: string | null;
            status: components["schemas"]["DisputeStatus"];
        };
        /**
         * DisputeStatus
         * @enum {string}
         */
        DisputeStatus: "OPEN" | "SELLER_RESPONDED" | "ANALYZED" | "RESOLVED" | "ESCALATED";
        /** ErrorBody */
        ErrorBody: {
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /** ErrorOut */
        ErrorOut: {
            error: components["schemas"]["ErrorBody"];
        };
        /** EvidenceOut */
        EvidenceOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Description Text */
            description_text: string;
            party: components["schemas"]["Party"];
        };
        /** FiredEvent */
        FiredEvent: {
            /** Event */
            event: string;
            /** Order Id */
            order_id: string;
        };
        /**
         * LedgerAccount
         * @enum {string}
         */
        LedgerAccount: "BUYER_WALLET" | "HOLD" | "SELLER_WALLET" | "REFUND";
        /** LedgerEntryOut */
        LedgerEntryOut: {
            account: components["schemas"]["LedgerAccount"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Credit */
            credit: number;
            /** Debit */
            debit: number;
            /** Reason */
            reason: string;
        };
        /** MetricsOut */
        MetricsOut: {
            /** Available */
            available: boolean;
            /** Reports */
            reports: {
                [key: string]: unknown;
            };
            /** Summary */
            summary: {
                [key: string]: unknown;
            } | null;
        };
        /** OrderOut */
        OrderOut: {
            /** Amount Bdt */
            amount_bdt: number;
            /** Buyer Id */
            buyer_id: string;
            /** Can Report Problem */
            can_report_problem: boolean;
            courier_status: components["schemas"]["CourierStatus"];
            /** Delivered At */
            delivered_at: string | null;
            /**
             * Delivery Code
             * @description Sandbox only: returned once, when the order is created.
             */
            delivery_code?: string | null;
            /** Dispute Ids */
            dispute_ids: string[];
            /** Hold Until */
            hold_until: string | null;
            /** Id */
            id: string;
            /** Ledger */
            ledger: components["schemas"]["LedgerEntryOut"][];
            /** Ledger Balanced */
            ledger_balanced: boolean;
            /**
             * Placed At
             * Format: date-time
             */
            placed_at: string;
            /** Product Category */
            product_category: string;
            /** Released At */
            released_at: string | null;
            /** Seller Id */
            seller_id: string;
            /** Server Time */
            server_time: string;
            status: components["schemas"]["OrderStatus"];
            /** Timeline */
            timeline: components["schemas"]["TimelineEventOut"][];
        };
        /**
         * OrderStatus
         * @enum {string}
         */
        OrderStatus: "HELD" | "DELIVERED" | "DISPUTABLE" | "DISPUTED" | "RELEASED" | "REFUNDED" | "ESCALATED";
        /**
         * Party
         * @enum {string}
         */
        Party: "BUYER" | "SELLER";
        /** QueueItemOut */
        QueueItemOut: {
            /** Amount Bdt */
            amount_bdt: number;
            /** Analyzed */
            analyzed: boolean;
            /** Dispute Id */
            dispute_id: string;
            /** Flags */
            flags: string[];
            /**
             * Opened At
             * Format: date-time
             */
            opened_at: string;
            /** Order Id */
            order_id: string;
            /** Recommendation */
            recommendation: string | null;
            /** Route */
            route: string | null;
            /** Seller Deadline */
            seller_deadline: string | null;
            status: components["schemas"]["DisputeStatus"];
        };
        /** ReasonOut */
        ReasonOut: {
            /** Direction */
            direction: string;
            /** Key */
            key: string;
            /** Text Bn */
            text_bn: string;
            /** Text En */
            text_en: string;
        };
        /** ScoreHistoryOut */
        ScoreHistoryOut: {
            /** Seller Id */
            seller_id: string;
            /** Snapshots */
            snapshots: components["schemas"]["SnapshotOut"][];
        };
        /** SellerPublic */
        SellerPublic: {
            /** Category */
            category: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Display Name */
            display_name: string;
            /** Id */
            id: string;
            /** Wallet No */
            wallet_no: string;
        };
        /** SellerResponseRequest */
        SellerResponseRequest: {
            /**
             * Evidence Text
             * @default
             */
            evidence_text: string;
            /** Response Text */
            response_text: string;
        };
        /** SnapshotOut */
        SnapshotOut: {
            band: components["schemas"]["TrustBand"];
            /** Created At */
            created_at: string;
            /** Id */
            id: number;
            /** Model Version */
            model_version: string;
            /** Reasons */
            reasons: components["schemas"]["ReasonOut"][];
            /** Score */
            score: number | null;
            trigger: components["schemas"]["SnapshotTrigger"];
        };
        /**
         * SnapshotTrigger
         * @enum {string}
         */
        SnapshotTrigger: "INITIAL" | "DISPUTE_RESOLVED" | "MANUAL";
        /** TimelineEventOut */
        TimelineEventOut: {
            /** Event */
            event: string;
            /** T */
            t: string;
        };
        /**
         * TrustBand
         * @enum {string}
         */
        TrustBand: "TRUSTED" | "CAUTION" | "HIGH_RISK" | "LIMITED_HISTORY";
        /** TrustChange */
        TrustChange: {
            after: components["schemas"]["SnapshotOut"];
            before: components["schemas"]["SnapshotOut"];
        };
        /** TrustCheckRequest */
        TrustCheckRequest: {
            /** Seller Id */
            seller_id?: string | null;
            /** Wallet No */
            wallet_no?: string | null;
        };
        /** TrustCheckResponse */
        TrustCheckResponse: {
            band: components["schemas"]["TrustBand"];
            /** Generated At */
            generated_at: string;
            /** Limited History */
            limited_history: boolean;
            /** Model Version */
            model_version: string;
            /** Reasons */
            reasons: components["schemas"]["ReasonOut"][];
            /** Requires Extra Confirmation */
            requires_extra_confirmation: boolean;
            /** Score */
            score: number | null;
            /** Seller Id */
            seller_id: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    case_view_api_analyst_disputes__dispute_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dispute_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalystCaseOut"];
                };
            };
            /** @description Bad request, for example a wrong delivery code */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not allowed in the current state */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Request body too large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Too many requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description A model is not available */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    decide_api_analyst_disputes__dispute_id__decision_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dispute_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecisionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionOut"];
                };
            };
            /** @description Bad request, for example a wrong delivery code */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not allowed in the current state */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Request body too large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Too many requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description A model is not available */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    queue_api_analyst_queue_get: {
        parameters: {
            query?: {
                route?: string | null;
                status?: components["schemas"]["DisputeStatus"] | null;
                min_amount_bdt?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueItemOut"][];
                };
            };
            /** @description Bad request, for example a wrong delivery code */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not allowed in the current state */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Request body too large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Too many requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description A model is not available */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    reset_api_demo_reset_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DemoResetRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DemoResetOut"];
                };
            };
            /** @description Bad request, for example a wrong delivery code */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not allowed in the current state */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Request body too large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Too many requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description A model is not available */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    create_dispute_api_disputes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDisputeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DisputeOut"];
                };
            };
            /** @description Bad request, for example a wrong delivery code */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not allowed in the current state */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Request body too large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Too many requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description A model is not available */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    get_dispute_api_disputes__dispute_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dispute_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DisputeOut"];
                };
            };
            /** @description Bad request, for example a wrong delivery code */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not allowed in the current state */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Request body too large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Too many requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description A model is not available */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    analyze_dispute_api_disputes__dispute_id__analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dispute_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisOut"];
                };
            };
            /** @description Bad request, for example a wrong delivery code */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not allowed in the current state */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Request body too large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Too many requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description A model is not available */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    buyer_evidence_api_disputes__dispute_id__buyer_evidence_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dispute_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BuyerEvidenceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DisputeOut"];
                };
            };
            /** @description Bad request, for example a wrong delivery code */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not allowed in the current state */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Request body too large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Too many requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description A model is not available */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    seller_response_api_disputes__dispute_id__seller_response_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dispute_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SellerResponseRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DisputeOut"];
                };
            };
            /** @description Bad request, for example a wrong delivery code */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not allowed in the current state */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Request body too large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Too many requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description A model is not available */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    metrics_summary_api_metrics_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricsOut"];
                };
            };
            /** @description Bad request, for example a wrong delivery code */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not allowed in the current state */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Request body too large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Too many requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description A model is not available */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    create_order_api_orders_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrderRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderOut"];
                };
            };
            /** @description Bad request, for example a wrong delivery code */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not allowed in the current state */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Request body too large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Too many requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description A model is not available */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    get_order_api_orders__order_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderOut"];
                };
            };
            /** @description Bad request, for example a wrong delivery code */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not allowed in the current state */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Request body too large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Too many requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description A model is not available */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    confirm_delivery_api_orders__order_id__confirm_delivery_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmDeliveryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderOut"];
                };
            };
            /** @description Bad request, for example a wrong delivery code */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not allowed in the current state */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Request body too large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Too many requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description A model is not available */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    search_sellers_api_sellers_search_get: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SellerPublic"][];
                };
            };
            /** @description Bad request, for example a wrong delivery code */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not allowed in the current state */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Request body too large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Too many requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description A model is not available */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    score_history_api_sellers__seller_id__score_history_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                seller_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScoreHistoryOut"];
                };
            };
            /** @description Bad request, for example a wrong delivery code */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not allowed in the current state */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Request body too large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Too many requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description A model is not available */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    advance_clock_api_sim_advance_clock_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdvanceClockRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClockOut"];
                };
            };
            /** @description Bad request, for example a wrong delivery code */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not allowed in the current state */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Request body too large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Too many requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description A model is not available */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    courier_event_api_sim_courier_event_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CourierEventRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderOut"];
                };
            };
            /** @description Bad request, for example a wrong delivery code */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not allowed in the current state */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Request body too large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Too many requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description A model is not available */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    trust_check_api_trust_check_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrustCheckRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrustCheckResponse"];
                };
            };
            /** @description Bad request, for example a wrong delivery code */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not allowed in the current state */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Request body too large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Too many requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description A model is not available */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
