type Dict = Record<string, string>

// Texts of the sandbox wallet. Every key exists in both languages (a test checks it), and the
// Bangla texts are written in Bengali script.

export const walletBn: Dict = {
  'w.brand': 'সেফঅর্ডার ওয়ালেট',
  'w.tagline': 'নিরাপদ অর্ডার, নিরাপদ পেমেন্ট',
  'w.back': 'পিছনে',
  'w.working': 'অপেক্ষা করুন...',
  'w.cancel': 'বাতিল',
  'w.yes': 'হ্যাঁ',
  'w.no': 'না',
  'w.copy': 'কপি',
  'w.copied': 'কপি হয়েছে',
  'w.home.back': 'হোমে ফিরুন',
  'w.nobackend': 'এই সাইটের সার্ভার এখনও ঠিক করা হয়নি (config.js)। অ্যাডমিনকে জানান।',

  'w.nav.home': 'হোম',
  'w.nav.account': 'অ্যাকাউন্ট',
  'w.nav.history': 'হিস্টরি',
  'w.nav.more': 'আরো',
  'w.nav.pay': 'পেমেন্ট',

  'w.welcome.title': 'স্বাগতম',
  'w.welcome.sub': 'ফোন নম্বর আর পিন দিয়ে অ্যাকাউন্ট খুলুন। এখানে সব টাকা কাল্পনিক ডেমো টাকা।',
  'w.welcome.twotabs': 'ক্রেতা ও বিক্রেতা দুজন হয়ে পরীক্ষা করতে একটি ট্যাবে ক্রেতা, আরেকটি ট্যাবে বিক্রেতা হিসেবে ঢুকুন। এক ট্যাবে থেকেও "আরো" থেকে অ্যাকাউন্ট বদলানো যায়।',
  'w.login': 'লগইন',
  'w.register': 'নতুন অ্যাকাউন্ট',
  'w.register.go': 'অ্যাকাউন্ট খুলুন',
  'w.register.bonus': 'নতুন অ্যাকাউন্টে স্বাগত উপহার হিসেবে কিছু ডেমো টাকা পাবেন।',
  'w.name': 'আপনার নাম',
  'w.phone': 'ফোন নম্বর',
  'w.pin': 'পিন (৫ সংখ্যা)',
  'w.pin.warning': 'সাবধান: এটা পরীক্ষামূলক সাইট। আপনার আসল ওয়ালেট বা ব্যাংকের পিন এখানে কখনো দেবেন না। যেকোনো বানানো ৫ সংখ্যা দিন।',
  'w.accounts.here': 'এই ব্রাউজারের অ্যাকাউন্ট',

  'w.balance': 'ব্যালেন্স',
  'w.held.line': 'আটকে আছে (বিক্রি বাবদ): {amount}',
  'w.todo.confirm': 'আপনার {n}টি অর্ডারে ডেলিভারি পেয়েছেন কিনা জানাতে হবে',
  'w.todo.claim': '{n}টি পেমেন্টের অর্ডার নম্বর বসানো বাকি',
  'w.tile.send': 'সেন্ড মানি',
  'w.tile.payment': 'মেক পেমেন্ট',
  'w.tile.add': 'অ্যাড মানি',
  'w.tile.history': 'হিস্টরি',
  'w.tile.orders': 'আমার অর্ডার',
  'w.tile.seller': 'বিক্রেতা',
  'w.tile.check': 'বিক্রেতা যাচাই',
  'w.tile.guide': 'গাইড',
  'w.how.title': 'সেফ অর্ডার কীভাবে কাজ করে',
  'w.how.1': 'ক্রেতা বিক্রেতার নম্বরে পেমেন্ট করে এবং চাইলে একটি অর্ডার নম্বর দেয়।',
  'w.how.2': 'টাকা বিক্রেতার কাছে যায়, কিন্তু আটকে থাকে। বিক্রেতা অর্ডার নম্বর বসিয়ে অর্ডারটি নেয়।',
  'w.how.3': 'ক্রেতা পণ্য পেয়ে অ্যাপে "ডেলিভারি পেয়েছি" চাপলে টাকা বিক্রেতার ওয়ালেটে যায়।',
  'w.how.4': 'সমস্যা হলে ক্রেতা রিপোর্ট করে। এআই বিশ্লেষণ করে, অ্যাডমিন সিদ্ধান্ত নেয়।',

  'w.pay.to': 'যাকে পাঠাবেন তার ফোন নম্বর',
  'w.pay.check': 'যাচাই করুন',
  'w.pay.seller': 'বিক্রেতা',
  'w.pay.self': 'নিজেকে টাকা পাঠানো যাবে না।',
  'w.pay.trust': 'বিক্রেতার ট্রাস্ট চেক',
  'w.pay.score': 'স্কোর: {score}/১০০',
  'w.pay.willhold': 'এই বিক্রেতাকে পাঠানো টাকা আটকে থাকবে। আপনি ডেলিভারি পেয়েছেন বললে বা নিয়ম অনুযায়ী তবেই বিক্রেতা টাকা পাবে।',
  'w.pay.notseller': 'এটি সাধারণ অ্যাকাউন্ট। টাকা সঙ্গে সঙ্গে পৌঁছে যাবে।',
  'w.pay.amount': 'টাকার পরিমাণ',
  'w.pay.have': 'আপনার ব্যালেন্স: {amount}',
  'w.pay.ref': 'অর্ডার নম্বর (ঐচ্ছিক)',
  'w.pay.ref.hint': 'যেমন: আপনার নিজের দেওয়া নম্বর',
  'w.pay.pin': 'নিশ্চিত করতে আপনার পিন দিন',
  'w.pay.risk': 'আমি বুঝেছি এই বিক্রেতা ঝুঁকিপূর্ণ, তবুও পাঠাতে চাই।',
  'w.pay.confirm': 'পাঠান {amount}',
  'w.pay.done': 'পেমেন্ট সম্পন্ন',
  'w.pay.held.note': 'টাকা বিক্রেতার কাছে গেছে কিন্তু আটকে আছে।',
  'w.pay.ordernumber': 'আপনার অর্ডার নম্বর',
  'w.pay.tellseller': 'এই নম্বরটি বিক্রেতাকে জানান। বিক্রেতা এটি বসালে অর্ডারটি নিশ্চিত হবে।',
  'w.pay.yourref': 'আপনার দেওয়া নম্বর',
  'w.pay.vieworder': 'অর্ডার দেখুন',
  'w.pay.sent.note': 'টাকা সঙ্গে সঙ্গে পৌঁছে গেছে।',

  'w.account.title': 'অ্যাকাউন্ট',
  'w.account.shop': 'দোকান: {name}',
  'w.wallet.primary': 'প্রাইমারি',
  'w.wallet.held': 'আটকে আছে',
  'w.wallet.held.explain': 'আটকে থাকা টাকা অন্যরা আপনার বিক্রির জন্য দিয়েছে। ক্রেতা ডেলিভারি পেয়েছে জানালে তা প্রাইমারিতে আসবে।',
  'w.add.title': 'ডেমো টাকা নিন',
  'w.add.sub': 'আরও নিতে পারবেন: {left}। এটা আসল পেমেন্ট নয়।',
  'w.add.done': '{amount} যোগ হয়েছে',

  'w.history.title': 'হিস্টরি',
  'w.history.tx': 'লেনদেন',
  'w.history.orders': 'অর্ডার',
  'w.history.empty': 'এখনও কোনো লেনদেন নেই।',
  'w.history.balance': 'ব্যালেন্স {amount}',
  'w.orders.bought': 'আমি যা কিনেছি',
  'w.orders.sold': 'আমি যা বিক্রি করেছি',
  'w.orders.none': 'এখনও কোনো অর্ডার নেই।',
  'w.orders.unclaimed': 'অর্ডার নম্বর বসানো বাকি',
  'w.orders.action.confirm': 'ডেলিভারি পেয়েছেন কিনা জানান',
  'w.orders.action.proof': 'ডেলিভারির প্রমাণ দিন',
  'w.tx.SIGNUP_BONUS': 'স্বাগত উপহার',
  'w.tx.ADD_MONEY': 'অ্যাড মানি',
  'w.tx.SEND_MONEY_OUT': 'সেন্ড মানি',
  'w.tx.SEND_MONEY_IN': 'টাকা পেয়েছেন',
  'w.tx.PAYMENT_HELD': 'পেমেন্ট (আটকে আছে)',
  'w.tx.PAYMENT_RECEIVED_HELD': 'পেমেন্ট এসেছে (আটকে আছে)',
  'w.tx.RELEASED': 'আটকানো টাকা ছাড়া হয়েছে',
  'w.tx.REFUNDED': 'টাকা ফেরত এসেছে',
  'w.tx.REFUND_OUT': 'টাকা ক্রেতাকে ফেরত গেছে',
  'w.tx.ADMIN_GRANT': 'অ্যাডমিনের দেওয়া ডেমো টাকা',

  'w.seller.become': 'বিক্রেতা হোন',
  'w.seller.become.sub': 'বিক্রেতা মোড চালু করলে অন্যরা আপনার নম্বরে পেমেন্ট করতে পারবে এবং সেই টাকা আটকে থাকবে।',
  'w.seller.shop': 'দোকানের নাম',
  'w.seller.category': 'পণ্যের ধরন',
  'w.seller.turnon': 'বিক্রেতা মোড চালু করুন',
  'w.seller.hub': 'বিক্রেতার ডেস্ক',
  'w.seller.held': 'আটকে আছে: {held} · প্রাইমারি: {balance}',
  'w.claim.title': 'অর্ডার নম্বর বসান',
  'w.claim.sub': 'ক্রেতা আপনাকে যে অর্ডার নম্বর জানিয়েছে সেটি লিখুন। ঠিক হলে অর্ডারটি আপনার হবে।',
  'w.claim.label': 'অর্ডার নম্বর',
  'w.claim.go': 'অর্ডার নিন',
  'w.claim.waiting': '{n}টি পেমেন্ট অপেক্ষায় আছে',
  'w.claim.deadline': 'এর আগে নম্বর না বসালে টাকা ফেরত যাবে: {time}',
  'w.cat.clothing': 'পোশাক',
  'w.cat.electronics': 'ইলেকট্রনিক্স',
  'w.cat.cosmetics': 'প্রসাধনী',
  'w.cat.household': 'ঘরের জিনিস',
  'w.cat.food': 'খাবার',
  'w.cat.shoes': 'জুতা',
  'w.cat.books': 'বই',
  'w.cat.accessories': 'অ্যাকসেসরিজ',

  'w.order.title': 'অর্ডার {id}',
  'w.order.seller': 'বিক্রেতা',
  'w.order.buyer': 'ক্রেতা',
  'w.order.placed': 'পেমেন্টের সময়',
  'w.order.claimed': 'অর্ডার নেওয়া হয়েছে',
  'w.order.notclaimed': 'এখনও না',
  'w.order.claimby': 'নম্বর বসানোর শেষ সময়',
  'w.order.timeline': 'কী কী হয়েছে',
  'w.status.HELD': 'আটকে আছে',
  'w.status.DELIVERED': 'ডেলিভারি হয়েছে',
  'w.status.DISPUTABLE': 'অভিযোগ করা যায়',
  'w.status.DISPUTED': 'অভিযোগ চলছে',
  'w.status.ESCALATED': 'জ্যেষ্ঠ পর্যালোচনায়',
  'w.status.RELEASED': 'বিক্রেতা টাকা পেয়েছে',
  'w.status.REFUNDED': 'ক্রেতাকে ফেরত',
  'w.status.HELD.about': 'টাকা আটকে আছে। ক্রেতা ডেলিভারি পেয়েছে জানালে তা বিক্রেতার কাছে যাবে।',
  'w.status.DELIVERED.about': 'ডেলিভারি হয়েছে। কিছুক্ষণ পর টাকা ছাড়া হবে।',
  'w.status.DISPUTABLE.about': 'সময়মতো ডেলিভারি হয়নি, ক্রেতা অভিযোগ করতে পারে।',
  'w.status.DISPUTED.about': 'অভিযোগ চলছে। অ্যাডমিন সিদ্ধান্ত না দেওয়া পর্যন্ত টাকা আটকে থাকবে।',
  'w.status.ESCALATED.about': 'ব্যাপারটি জ্যেষ্ঠ পর্যালোচনায় আছে।',
  'w.status.RELEASED.about': 'টাকা বিক্রেতার ওয়ালেটে চলে গেছে।',
  'w.status.REFUNDED.about': 'টাকা ক্রেতাকে ফেরত দেওয়া হয়েছে।',

  'w.accept.title': 'পণ্য কি হাতে পেয়েছেন?',
  'w.accept.sub': 'পণ্য ঠিকঠাক হাতে পেলে নিচের বোতাম চাপুন। তখন টাকা বিক্রেতার কাছে চলে যাবে এবং ফেরানো যাবে না।',
  'w.accept.button': 'ডেলিভারি পেয়েছি',
  'w.accept.sure': 'নিশ্চিত? টাকা এখনই বিক্রেতাকে দেওয়া হবে।',
  'w.accept.yes': 'হ্যাঁ, পেয়েছি',
  'w.report.open': 'সমস্যা জানান',
  'w.report.title': 'সমস্যার রিপোর্ট',
  'w.report.sub': 'কী হয়েছে লিখুন। এআই সঙ্গে সঙ্গে দেখবে, তারপর অ্যাডমিন সিদ্ধান্ত দেবেন। তার আগে টাকা আটকে থাকবে।',
  'w.report.what': 'কী সমস্যা হয়েছে?',
  'w.report.send': 'রিপোর্ট পাঠান',
  'w.claimtype.NOT_RECEIVED': 'পণ্য পাইনি',
  'w.claimtype.WRONG_ITEM': 'ভুল পণ্য',
  'w.claimtype.DAMAGED': 'ভাঙা বা নষ্ট',
  'w.claimtype.NOT_AS_DESCRIBED': 'বর্ণনার সাথে মেলে না',
  'w.claimtype.OTHER': 'অন্য কিছু',

  'w.proof.title': 'ডেলিভারির প্রমাণ',
  'w.proof.tracking': 'ট্র্যাকিং নম্বর',
  'w.proof.note': 'নোট',
  'w.proof.when': 'জমা দেওয়ার সময়',
  'w.proof.photo': 'রসিদ বা প্যাকেটের ছবি',
  'w.proof.photo.bad': 'ছবিটি ব্যবহার করা গেল না। আরেকটি ছবি দিন।',
  'w.proof.show': 'ছবি দেখুন',
  'w.proof.flags': 'সতর্কতা পাওয়া গেছে',
  'w.proof.flags.admin': 'এই প্রমাণ নিজে থেকে টাকা ছাড়াবে না, অ্যাডমিন দেখবেন।',
  'w.proof.auto': 'ক্রেতা চুপ থাকলে এই সময়ের পর টাকা নিজে থেকে বিক্রেতার কাছে যাবে: {time}',
  'w.proof.form.title': 'ডেলিভারির প্রমাণ দিন',
  'w.proof.form.sub': 'পণ্য পাঠিয়ে থাকলে ট্র্যাকিং নম্বর আর রসিদের ছবি দিন। ক্রেতা ৭২ ঘণ্টা কিছু না জানালে এবং প্রমাণে সমস্যা না থাকলে টাকা ছাড়া হবে।',
  'w.proof.send': 'প্রমাণ জমা দিন',
  'w.flag.NO_IMAGE': 'কোনো ছবি দেওয়া হয়নি',
  'w.flag.BAD_TRACKING_FORMAT': 'ট্র্যাকিং নম্বরটি ঠিক মনে হচ্ছে না',
  'w.flag.DUPLICATE_IMAGE': 'একই ছবি অন্য অর্ডারেও ব্যবহার হয়েছে',
  'w.flag.DUPLICATE_TRACKING': 'একই ট্র্যাকিং নম্বর অন্য অর্ডারেও আছে',
  'w.flag.HIGH_RISK_SELLER': 'বিক্রেতা ঝুঁকিপূর্ণ হিসেবে ধরা পড়েছে',

  'w.dispute.title': 'অভিযোগ {id}',
  'w.dispute.status.OPEN': 'খোলা, বিক্রেতার জবাবের অপেক্ষায়',
  'w.dispute.status.SELLER_RESPONDED': 'বিক্রেতা জবাব দিয়েছে',
  'w.dispute.status.ANALYZED': 'এআই বিশ্লেষণ হয়েছে, অ্যাডমিনের সিদ্ধান্তের অপেক্ষায়',
  'w.dispute.status.RESOLVED': 'সিদ্ধান্ত হয়ে গেছে',
  'w.dispute.status.ESCALATED': 'জ্যেষ্ঠ পর্যালোচনায়',
  'w.dispute.claim': 'ক্রেতার অভিযোগ',
  'w.dispute.seller': 'বিক্রেতার জবাব',
  'w.dispute.deadline': 'বিক্রেতার জবাবের শেষ সময়: {time}',
  'w.dispute.ai': 'এআই শুধু পরামর্শ দেয়। টাকা কোথায় যাবে তা ঠিক করেন অ্যাডমিন।',
  'w.dispute.answer.seller': 'আপনার জবাব লিখুন',
  'w.dispute.answer.buyer': 'আরও প্রমাণ বা তথ্য যোগ করুন',
  'w.dispute.send': 'পাঠান',
  'w.party.BUYER': 'ক্রেতা',
  'w.party.SELLER': 'বিক্রেতা',

  'w.more.settings': 'সেটিংস',
  'w.more.pin': 'পিন পরিবর্তন',
  'w.more.pin.old': 'বর্তমান পিন',
  'w.more.pin.new': 'নতুন পিন',
  'w.more.pin.save': 'পিন বদলান',
  'w.more.pin.done': 'পিন বদলানো হয়েছে।',
  'w.more.language': 'ভাষা পরিবর্তন',
  'w.more.accounts': 'অ্যাকাউন্ট',
  'w.more.switchto': '{name}-এ যান',
  'w.more.addaccount': 'আরেকটি অ্যাকাউন্ট খুলুন',
  'w.more.help': 'সাহায্য ও টুল',
  'w.more.admin': 'অ্যাডমিন প্যানেল',
  'w.more.logout': 'লগআউট',

  'w.guide.title': 'রোল-প্লে গাইড',
  'w.guide.intro': 'এই সাইটে আপনি ক্রেতা, বিক্রেতা ও অ্যাডমিন হয়ে পুরো সেফ অর্ডার পরীক্ষা করতে পারবেন। সব টাকা ডেমো টাকা।',
  'w.guide.tip.tabs': 'এক ব্রাউজারে দুটো ট্যাব খুলে একটিতে ক্রেতা, অন্যটিতে বিক্রেতা হিসেবে ঢুকুন।',
  'w.guide.tip.switch': 'এক ট্যাবে থাকলে "আরো" মেনু থেকে অ্যাকাউন্ট বদলান।',
  'w.guide.tip.admin': 'অ্যাডমিনের নম্বর ও পিন সাইটের মালিকের কাছে থাকে। অ্যাডমিন সময় এগিয়ে দেখাতে পারে (৭২ ঘণ্টা পরে কী হয়)।',
  'w.guide.quick.title': 'এক ক্লিকে ডেমো অ্যাকাউন্ট',
  'w.guide.quick.sub': 'একজন ক্রেতা ও একজন বিক্রেতার অ্যাকাউন্ট নিজে থেকে খুলে দেওয়া হবে।',
  'w.guide.quick.go': 'ডেমো অ্যাকাউন্ট বানান',
  'w.guide.quick.done': 'তৈরি হয়েছে:',
  'w.guide.quick.buyer': 'ক্রেতা',
  'w.guide.quick.seller': 'বিক্রেতা',
  'w.guide.quick.pin': 'পিন',
  'w.guide.quick.asbuyer': 'ক্রেতা হয়ে যান',
  'w.guide.quick.asseller': 'বিক্রেতা হয়ে যান',
  'w.guide.stories': 'পাঁচটি গল্প চেষ্টা করুন',
  'w.guide.s.honest.title': 'সৎ বিক্রি',
  'w.guide.s.honest.steps': 'ক্রেতা বিক্রেতার নম্বরে পেমেন্ট করে অর্ডার নম্বর পায় → বিক্রেতা "বিক্রেতা" থেকে নম্বর বসায় → ক্রেতা "ডেলিভারি পেয়েছি" চাপে → টাকা বিক্রেতার প্রাইমারিতে যায়।',
  'w.guide.s.silent.title': 'ক্রেতা চুপ, বিক্রেতার প্রমাণ',
  'w.guide.s.silent.steps': 'বিক্রেতা নম্বর বসিয়ে ট্র্যাকিং নম্বর ও ছবি দেয় → অ্যাডমিন "সময়" থেকে ৭২ ঘণ্টা এগিয়ে দেয় → প্রমাণ ঠিক থাকলে টাকা নিজে থেকে বিক্রেতার কাছে যায়।',
  'w.guide.s.unclaimed.title': 'বিক্রেতা অর্ডার নেয়নি',
  'w.guide.s.unclaimed.steps': 'ক্রেতা পেমেন্ট করে, বিক্রেতা নম্বর বসায় না → অ্যাডমিন ২৪ ঘণ্টা এগিয়ে দেয় → টাকা ক্রেতার কাছে ফেরত আসে।',
  'w.guide.s.falseclaim.title': 'ক্রেতার ভুল অভিযোগ',
  'w.guide.s.falseclaim.steps': 'ক্রেতা "সমস্যা জানান" চাপে, এআই বিশ্লেষণ করে → বিক্রেতা জবাব ও প্রমাণ দেয় → অ্যাডমিন বিশ্লেষক কনসোলে দেখে সিদ্ধান্ত নেয়।',
  'w.guide.s.fakeproof.title': 'ভুয়া প্রমাণ',
  'w.guide.s.fakeproof.steps': 'বিক্রেতা দুই অর্ডারে একই ছবি বা একই ট্র্যাকিং নম্বর দেয় → সিস্টেম সতর্কতা দেয় এবং নিজে টাকা ছাড়ে না → অ্যাডমিন দেখে ফেরত বা ছাড়ের সিদ্ধান্ত নেয়।',

  'w.admin.title': 'অ্যাডমিন প্যানেল',
  'w.admin.stat.users': 'ব্যবহারকারী',
  'w.admin.stat.sellers': 'বিক্রেতা',
  'w.admin.stat.held': 'আটকে থাকা টাকা',
  'w.admin.stat.proofs': 'প্রমাণের অপেক্ষায়',
  'w.admin.stat.disputes': 'খোলা অভিযোগ',
  'w.admin.stat.open': 'চলমান অর্ডার',
  'w.admin.now': 'সিস্টেমের সময়: {time}',
  'w.admin.disputes': 'অভিযোগের কনসোল',
  'w.admin.disputes.sub': 'এআই-এর বিশ্লেষণ দেখে অভিযোগে সিদ্ধান্ত দিন।',
  'w.admin.tab.orders': 'অর্ডার',
  'w.admin.tab.users': 'ব্যবহারকারী',
  'w.admin.tab.time': 'সময়',
  'w.admin.onlyopen': 'শুধু চলমান অর্ডার',
  'w.admin.dispute': 'অভিযোগ',
  'w.admin.noflags': 'প্রমাণে কোনো সতর্কতা নেই',
  'w.admin.note': 'সিদ্ধান্তের কারণ (লিখতেই হবে)',
  'w.admin.release': 'বিক্রেতাকে দিন',
  'w.admin.refund': 'ক্রেতাকে ফেরত',
  'w.admin.role': 'অ্যাডমিন',
  'w.admin.frozen': 'বন্ধ',
  'w.admin.freeze': 'অ্যাকাউন্ট বন্ধ করুন',
  'w.admin.unfreeze': 'আবার চালু করুন',
  'w.admin.grant': '+১,০০০ ডেমো টাকা',
  'w.time.title': 'সময় এগিয়ে দিন',
  'w.time.sub': 'ডেমোর জন্য ঘড়ি এগিয়ে দিলে সময়ভিত্তিক নিয়মগুলো (২৪ ঘণ্টায় অর্ডার না নেওয়া, ৭২ ঘণ্টা ক্রেতার চুপ থাকা) কাজ করে।',
  'w.time.hours': 'ঘণ্টা',
  'w.time.nothing': 'এবার কিছু ঘটেনি।',
  'w.time.event.SELLER_NO_CLAIM': 'বিক্রেতা অর্ডার নেয়নি, টাকা ক্রেতাকে ফেরত',
  'w.time.event.PROOF_RELEASE': 'প্রমাণ ঠিক ছিল, টাকা বিক্রেতার কাছে গেছে',
  'w.time.event.HOLD_EXPIRED': 'আটকে রাখার সময় শেষ, টাকা ছাড়া হয়েছে',
  'w.time.event.DISPATCH_DEADLINE_MISSED': 'পাঠানোর সময় পার হয়েছে',

  'event.SELLER_CLAIMED_ORDER': 'বিক্রেতা অর্ডার নম্বর বসিয়েছে',
  'event.SELLER_PROOF_SUBMITTED': 'বিক্রেতা ডেলিভারির প্রমাণ দিয়েছে',
  'event.BUYER_ACCEPTED_FUNDS_RELEASED': 'ক্রেতা ডেলিভারি পেয়েছে, টাকা বিক্রেতাকে দেওয়া হয়েছে',
  'event.PROOF_ACCEPTED_FUNDS_RELEASED': 'প্রমাণ গ্রহণ হয়েছে, টাকা বিক্রেতাকে দেওয়া হয়েছে',
  'event.UNCLAIMED_REFUNDED_TO_BUYER': 'অর্ডার নেওয়া হয়নি, টাকা ক্রেতাকে ফেরত',

  'w.err.WRONG_PIN': 'ফোন নম্বর বা পিন ঠিক নয়।',
  'w.err.ACCOUNT_LOCKED': 'অনেকবার ভুল পিন দেওয়া হয়েছে। কিছুক্ষণ পর আবার চেষ্টা করুন।',
  'w.err.ACCOUNT_FROZEN': 'এই অ্যাকাউন্ট অ্যাডমিন বন্ধ করে রেখেছে।',
  'w.err.PHONE_TAKEN': 'এই নম্বরে আগেই অ্যাকাউন্ট আছে। লগইন করুন।',
  'w.err.NOT_SIGNED_IN': 'আগে লগইন করুন।',
  'w.err.INSUFFICIENT_FUNDS': 'ব্যালেন্সে এত টাকা নেই।',
  'w.err.ADD_MONEY_LIMIT': 'এই অ্যাকাউন্টের ডেমো টাকা নেওয়ার সীমা শেষ।',
  'w.err.RISK_CONFIRMATION_REQUIRED': 'এই বিক্রেতা ঝুঁকিপূর্ণ। ঝুঁকির ঘরে টিক দিয়ে নিশ্চিত করুন।',
  'w.err.RECIPIENT_FROZEN': 'এই অ্যাকাউন্টে এখন টাকা পাঠানো যাবে না।',
  'w.err.NOT_A_SELLER': 'আগে বিক্রেতা মোড চালু করুন।',
  'w.err.NOT_CLAIMED': 'আগে অর্ডার নম্বর বসান।',
  'w.err.FORBIDDEN': 'এটা আপনার অর্ডার নয়।',
  'w.err.ADMIN_ONLY': 'শুধু অ্যাডমিন এটা করতে পারে।',
  'w.err.NOT_FOUND': 'পাওয়া যায়নি। নম্বরটি আবার দেখুন।',
  'w.err.VALIDATION_ERROR': 'দেওয়া তথ্যে ভুল আছে। ঘরগুলো আবার দেখুন।',
  'w.err.ILLEGAL_STATE': 'এই অবস্থায় এটা করা যাবে না।',
  'w.err.RATE_LIMITED': 'অনেক বেশি চেষ্টা হয়েছে। একটু পর আবার করুন।',
  'w.err.PAYLOAD_TOO_LARGE': 'ছবি বা লেখাটি অনেক বড়।',
  'w.err.NETWORK': 'সার্ভারের সঙ্গে যোগাযোগ করা যাচ্ছে না।',
  'w.err.SERVICE_STARTING': 'সার্ভার চালু হচ্ছে। এক মিনিট পর আবার চেষ্টা করুন।',
}

export const walletEn: Dict = {
  'w.brand': 'SafeOrder Wallet',
  'w.tagline': 'Safe orders, safe payments',
  'w.back': 'Back',
  'w.working': 'Please wait...',
  'w.cancel': 'Cancel',
  'w.yes': 'Yes',
  'w.no': 'No',
  'w.copy': 'Copy',
  'w.copied': 'Copied',
  'w.home.back': 'Back to home',
  'w.nobackend': 'The server of this site is not set up yet (config.js). Please tell the admin.',

  'w.nav.home': 'Home',
  'w.nav.account': 'Account',
  'w.nav.history': 'History',
  'w.nav.more': 'More',
  'w.nav.pay': 'Pay',

  'w.welcome.title': 'Welcome',
  'w.welcome.sub': 'Open an account with a phone number and a PIN. All money here is pretend demo money.',
  'w.welcome.twotabs': 'To test as buyer and seller, sign in as the buyer in one tab and as the seller in another tab. In one tab you can also switch account from "More".',
  'w.login': 'Sign in',
  'w.register': 'New account',
  'w.register.go': 'Open account',
  'w.register.bonus': 'A new account gets some demo money as a welcome gift.',
  'w.name': 'Your name',
  'w.phone': 'Phone number',
  'w.pin': 'PIN (5 digits)',
  'w.pin.warning': 'Careful: this is a test site. Never enter the PIN of your real wallet or bank here. Use any made-up 5 digits.',
  'w.accounts.here': 'Accounts in this browser',

  'w.balance': 'Balance',
  'w.held.line': 'Held (from sales): {amount}',
  'w.todo.confirm': 'You must say whether {n} of your orders arrived',
  'w.todo.claim': '{n} payment(s) are waiting for the order number',
  'w.tile.send': 'Send Money',
  'w.tile.payment': 'Make Payment',
  'w.tile.add': 'Add Money',
  'w.tile.history': 'History',
  'w.tile.orders': 'My Orders',
  'w.tile.seller': 'Seller',
  'w.tile.check': 'Check Seller',
  'w.tile.guide': 'Guide',
  'w.how.title': 'How Safe Order works',
  'w.how.1': 'The buyer pays the seller\'s number and can add an order number.',
  'w.how.2': 'The money goes to the seller but stays held. The seller enters the order number to take the order.',
  'w.how.3': 'When the goods arrive, the buyer presses "I received it" and the money goes to the seller\'s wallet.',
  'w.how.4': 'If there is a problem the buyer reports it. The AI analyses it and an admin decides.',

  'w.pay.to': 'Phone number of the person you pay',
  'w.pay.check': 'Check',
  'w.pay.seller': 'Seller',
  'w.pay.self': 'You cannot send money to yourself.',
  'w.pay.trust': 'Seller trust check',
  'w.pay.score': 'Score: {score}/100',
  'w.pay.willhold': 'Money sent to this seller is held. The seller gets it only when you say the delivery arrived, or by the rules.',
  'w.pay.notseller': 'This is a normal account. The money arrives at once.',
  'w.pay.amount': 'Amount',
  'w.pay.have': 'Your balance: {amount}',
  'w.pay.ref': 'Order number (optional)',
  'w.pay.ref.hint': 'For example a number you choose',
  'w.pay.pin': 'Enter your PIN to confirm',
  'w.pay.risk': 'I understand this seller looks high risk, and I still want to pay.',
  'w.pay.confirm': 'Pay {amount}',
  'w.pay.done': 'Payment done',
  'w.pay.held.note': 'The money went to the seller but is held.',
  'w.pay.ordernumber': 'Your order number',
  'w.pay.tellseller': 'Tell the seller this number. When the seller enters it, the order is confirmed.',
  'w.pay.yourref': 'Your own number',
  'w.pay.vieworder': 'View order',
  'w.pay.sent.note': 'The money arrived at once.',

  'w.account.title': 'Account',
  'w.account.shop': 'Shop: {name}',
  'w.wallet.primary': 'Primary',
  'w.wallet.held': 'Held',
  'w.wallet.held.explain': 'Held money was paid by others for your sales. It moves to Primary when the buyer says the delivery arrived.',
  'w.add.title': 'Take demo money',
  'w.add.sub': 'You can still take: {left}. This is not a real payment.',
  'w.add.done': '{amount} added',

  'w.history.title': 'History',
  'w.history.tx': 'Transactions',
  'w.history.orders': 'Orders',
  'w.history.empty': 'No transactions yet.',
  'w.history.balance': 'Balance {amount}',
  'w.orders.bought': 'What I bought',
  'w.orders.sold': 'What I sold',
  'w.orders.none': 'No orders yet.',
  'w.orders.unclaimed': 'Waiting for the order number',
  'w.orders.action.confirm': 'Say whether it arrived',
  'w.orders.action.proof': 'Give delivery proof',
  'w.tx.SIGNUP_BONUS': 'Welcome gift',
  'w.tx.ADD_MONEY': 'Add Money',
  'w.tx.SEND_MONEY_OUT': 'Send Money',
  'w.tx.SEND_MONEY_IN': 'Money received',
  'w.tx.PAYMENT_HELD': 'Payment (held)',
  'w.tx.PAYMENT_RECEIVED_HELD': 'Payment received (held)',
  'w.tx.RELEASED': 'Held money released',
  'w.tx.REFUNDED': 'Money refunded',
  'w.tx.REFUND_OUT': 'Money returned to the buyer',
  'w.tx.ADMIN_GRANT': 'Demo money from the admin',

  'w.seller.become': 'Become a seller',
  'w.seller.become.sub': 'With seller mode on, others can pay your number and that money is held.',
  'w.seller.shop': 'Shop name',
  'w.seller.category': 'What you sell',
  'w.seller.turnon': 'Turn on seller mode',
  'w.seller.hub': 'Seller desk',
  'w.seller.held': 'Held: {held} · Primary: {balance}',
  'w.claim.title': 'Enter the order number',
  'w.claim.sub': 'Type the order number the buyer gave you. If it is right, the order becomes yours.',
  'w.claim.label': 'Order number',
  'w.claim.go': 'Take the order',
  'w.claim.waiting': '{n} payment(s) waiting',
  'w.claim.deadline': 'If the number is not entered before this, the money goes back: {time}',
  'w.cat.clothing': 'Clothing',
  'w.cat.electronics': 'Electronics',
  'w.cat.cosmetics': 'Cosmetics',
  'w.cat.household': 'Household',
  'w.cat.food': 'Food',
  'w.cat.shoes': 'Shoes',
  'w.cat.books': 'Books',
  'w.cat.accessories': 'Accessories',

  'w.order.title': 'Order {id}',
  'w.order.seller': 'Seller',
  'w.order.buyer': 'Buyer',
  'w.order.placed': 'Paid at',
  'w.order.claimed': 'Order taken',
  'w.order.notclaimed': 'Not yet',
  'w.order.claimby': 'Order number due by',
  'w.order.timeline': 'What happened',
  'w.status.HELD': 'Held',
  'w.status.DELIVERED': 'Delivered',
  'w.status.DISPUTABLE': 'Can be disputed',
  'w.status.DISPUTED': 'Dispute open',
  'w.status.ESCALATED': 'Senior review',
  'w.status.RELEASED': 'Seller paid',
  'w.status.REFUNDED': 'Refunded to buyer',
  'w.status.HELD.about': 'The money is held. It goes to the seller when the buyer says it arrived.',
  'w.status.DELIVERED.about': 'Delivered. The money will be released shortly.',
  'w.status.DISPUTABLE.about': 'Delivery was late, the buyer may open a dispute.',
  'w.status.DISPUTED.about': 'A dispute is open. The money stays held until an admin decides.',
  'w.status.ESCALATED.about': 'This is under senior review.',
  'w.status.RELEASED.about': 'The money went to the seller\'s wallet.',
  'w.status.REFUNDED.about': 'The money was returned to the buyer.',

  'w.accept.title': 'Did the goods arrive?',
  'w.accept.sub': 'If you received the goods properly, press the button. The money then goes to the seller and cannot be taken back.',
  'w.accept.button': 'I received it',
  'w.accept.sure': 'Sure? The money is given to the seller now.',
  'w.accept.yes': 'Yes, received',
  'w.report.open': 'Report a problem',
  'w.report.title': 'Problem report',
  'w.report.sub': 'Write what happened. The AI looks at it at once, then an admin decides. Until then the money stays held.',
  'w.report.what': 'What went wrong?',
  'w.report.send': 'Send report',
  'w.claimtype.NOT_RECEIVED': 'Not received',
  'w.claimtype.WRONG_ITEM': 'Wrong item',
  'w.claimtype.DAMAGED': 'Damaged',
  'w.claimtype.NOT_AS_DESCRIBED': 'Not as described',
  'w.claimtype.OTHER': 'Something else',

  'w.proof.title': 'Delivery proof',
  'w.proof.tracking': 'Tracking number',
  'w.proof.note': 'Note',
  'w.proof.when': 'Submitted at',
  'w.proof.photo': 'Photo of the receipt or parcel',
  'w.proof.photo.bad': 'This photo could not be used. Try another one.',
  'w.proof.show': 'Show photo',
  'w.proof.flags': 'Warnings found',
  'w.proof.flags.admin': 'This proof will not release the money by itself; an admin will look at it.',
  'w.proof.auto': 'If the buyer stays silent, the money goes to the seller by itself after: {time}',
  'w.proof.form.title': 'Give delivery proof',
  'w.proof.form.sub': 'If you have sent the goods, give the tracking number and a photo of the receipt. If the buyer says nothing for 72 hours and the proof has no problem, the money is released.',
  'w.proof.send': 'Submit proof',
  'w.flag.NO_IMAGE': 'No photo was given',
  'w.flag.BAD_TRACKING_FORMAT': 'The tracking number does not look right',
  'w.flag.DUPLICATE_IMAGE': 'The same photo was used for another order',
  'w.flag.DUPLICATE_TRACKING': 'The same tracking number is on another order',
  'w.flag.HIGH_RISK_SELLER': 'The seller is flagged as high risk',

  'w.dispute.title': 'Dispute {id}',
  'w.dispute.status.OPEN': 'Open, waiting for the seller\'s answer',
  'w.dispute.status.SELLER_RESPONDED': 'The seller answered',
  'w.dispute.status.ANALYZED': 'AI analysis done, waiting for the admin\'s decision',
  'w.dispute.status.RESOLVED': 'Decided',
  'w.dispute.status.ESCALATED': 'Senior review',
  'w.dispute.claim': 'The buyer\'s complaint',
  'w.dispute.seller': 'The seller\'s answer',
  'w.dispute.deadline': 'The seller must answer by: {time}',
  'w.dispute.ai': 'The AI only suggests. An admin decides where the money goes.',
  'w.dispute.answer.seller': 'Write your answer',
  'w.dispute.answer.buyer': 'Add more evidence or details',
  'w.dispute.send': 'Send',
  'w.party.BUYER': 'Buyer',
  'w.party.SELLER': 'Seller',

  'w.more.settings': 'Settings',
  'w.more.pin': 'Change PIN',
  'w.more.pin.old': 'Current PIN',
  'w.more.pin.new': 'New PIN',
  'w.more.pin.save': 'Change PIN',
  'w.more.pin.done': 'PIN changed.',
  'w.more.language': 'Change language',
  'w.more.accounts': 'Accounts',
  'w.more.switchto': 'Switch to {name}',
  'w.more.addaccount': 'Open another account',
  'w.more.help': 'Help and tools',
  'w.more.admin': 'Admin panel',
  'w.more.logout': 'Sign out',

  'w.guide.title': 'Role-play guide',
  'w.guide.intro': 'On this site you can try the whole Safe Order as buyer, seller and admin. All money is demo money.',
  'w.guide.tip.tabs': 'Open two tabs in one browser: the buyer in one, the seller in the other.',
  'w.guide.tip.switch': 'In one tab, switch account from the "More" menu.',
  'w.guide.tip.admin': 'The admin number and PIN are with the site owner. The admin can move time forward (what happens after 72 hours).',
  'w.guide.quick.title': 'Demo accounts in one click',
  'w.guide.quick.sub': 'One buyer account and one seller account are opened for you.',
  'w.guide.quick.go': 'Create demo accounts',
  'w.guide.quick.done': 'Created:',
  'w.guide.quick.buyer': 'Buyer',
  'w.guide.quick.seller': 'Seller',
  'w.guide.quick.pin': 'PIN',
  'w.guide.quick.asbuyer': 'Be the buyer',
  'w.guide.quick.asseller': 'Be the seller',
  'w.guide.stories': 'Try five stories',
  'w.guide.s.honest.title': 'An honest sale',
  'w.guide.s.honest.steps': 'The buyer pays the seller\'s number and gets an order number → the seller enters it in "Seller" → the buyer presses "I received it" → the money goes to the seller\'s Primary wallet.',
  'w.guide.s.silent.title': 'Silent buyer, seller proof',
  'w.guide.s.silent.steps': 'The seller enters the number and gives a tracking number and photo → the admin moves time 72 hours forward in "Time" → if the proof is fine the money goes to the seller by itself.',
  'w.guide.s.unclaimed.title': 'The seller never takes the order',
  'w.guide.s.unclaimed.steps': 'The buyer pays, the seller does not enter the number → the admin moves time 24 hours forward → the money comes back to the buyer.',
  'w.guide.s.falseclaim.title': 'A false claim by the buyer',
  'w.guide.s.falseclaim.steps': 'The buyer presses "Report a problem" and the AI analyses it → the seller answers with evidence → the admin looks in the analyst console and decides.',
  'w.guide.s.fakeproof.title': 'Fake proof',
  'w.guide.s.fakeproof.steps': 'The seller gives the same photo or tracking number on two orders → the system warns and does not release the money itself → the admin looks and decides to refund or release.',

  'w.admin.title': 'Admin panel',
  'w.admin.stat.users': 'Users',
  'w.admin.stat.sellers': 'Sellers',
  'w.admin.stat.held': 'Money held',
  'w.admin.stat.proofs': 'Waiting for proof check',
  'w.admin.stat.disputes': 'Open disputes',
  'w.admin.stat.open': 'Orders in progress',
  'w.admin.now': 'System time: {time}',
  'w.admin.disputes': 'Dispute console',
  'w.admin.disputes.sub': 'Look at the AI analysis and decide on disputes.',
  'w.admin.tab.orders': 'Orders',
  'w.admin.tab.users': 'Users',
  'w.admin.tab.time': 'Time',
  'w.admin.onlyopen': 'Only orders in progress',
  'w.admin.dispute': 'Dispute',
  'w.admin.noflags': 'The proof has no warnings',
  'w.admin.note': 'Reason for the decision (required)',
  'w.admin.release': 'Give to seller',
  'w.admin.refund': 'Refund buyer',
  'w.admin.role': 'admin',
  'w.admin.frozen': 'frozen',
  'w.admin.freeze': 'Freeze account',
  'w.admin.unfreeze': 'Unfreeze',
  'w.admin.grant': '+1,000 demo money',
  'w.time.title': 'Move time forward',
  'w.time.sub': 'For the demo, moving the clock forward makes the time rules work (24 hours to enter the order number, 72 hours of buyer silence).',
  'w.time.hours': 'hours',
  'w.time.nothing': 'Nothing happened this time.',
  'w.time.event.SELLER_NO_CLAIM': 'The seller never took the order, money returned to the buyer',
  'w.time.event.PROOF_RELEASE': 'The proof was fine, money went to the seller',
  'w.time.event.HOLD_EXPIRED': 'The hold ended, money released',
  'w.time.event.DISPATCH_DEADLINE_MISSED': 'The dispatch time passed',

  'event.SELLER_CLAIMED_ORDER': 'The seller entered the order number',
  'event.SELLER_PROOF_SUBMITTED': 'The seller gave delivery proof',
  'event.BUYER_ACCEPTED_FUNDS_RELEASED': 'The buyer received the goods, money given to the seller',
  'event.PROOF_ACCEPTED_FUNDS_RELEASED': 'The proof was accepted, money given to the seller',
  'event.UNCLAIMED_REFUNDED_TO_BUYER': 'The order was not taken, money returned to the buyer',

  'w.err.WRONG_PIN': 'The phone number or PIN is wrong.',
  'w.err.ACCOUNT_LOCKED': 'Too many wrong PINs. Try again in a while.',
  'w.err.ACCOUNT_FROZEN': 'This account is frozen by an admin.',
  'w.err.PHONE_TAKEN': 'This number already has an account. Sign in.',
  'w.err.NOT_SIGNED_IN': 'Please sign in first.',
  'w.err.INSUFFICIENT_FUNDS': 'There is not enough balance.',
  'w.err.ADD_MONEY_LIMIT': 'The demo money limit of this account is used up.',
  'w.err.RISK_CONFIRMATION_REQUIRED': 'This seller is high risk. Tick the risk box to confirm.',
  'w.err.RECIPIENT_FROZEN': 'This account cannot receive money now.',
  'w.err.NOT_A_SELLER': 'Turn on seller mode first.',
  'w.err.NOT_CLAIMED': 'Enter the order number first.',
  'w.err.FORBIDDEN': 'This is not your order.',
  'w.err.ADMIN_ONLY': 'Only an admin can do this.',
  'w.err.NOT_FOUND': 'Not found. Check the number again.',
  'w.err.VALIDATION_ERROR': 'Some details are wrong. Please check the fields.',
  'w.err.ILLEGAL_STATE': 'This is not possible in the current state.',
  'w.err.RATE_LIMITED': 'Too many tries. Please wait a little.',
  'w.err.PAYLOAD_TOO_LARGE': 'The photo or the text is too large.',
  'w.err.NETWORK': 'Cannot reach the server.',
  'w.err.SERVICE_STARTING': 'The service is starting. Try again in a minute.',
}
