"""Generate the documentation set (BLUEPRINT.md Section 16) with numbers read from reports/*.json.

Usage (repository root): PYTHONPATH=backend:. python -m scripts.build_docs   (or `make docs`)
Writes into docs/: model_card_trust.md, dataset_card_synthetic_sellers.md, evaluation_protocol.md,
responsible_ai.md, licence_register.md and README.md (an index with the status of every document).

Every number comes from a report file; the prose says what the report cannot say. Run
`make eval` first. Do not edit the generated files by hand.
"""

import json
from importlib import metadata
from pathlib import Path
from typing import Any

from app.config import load_config

REPO = Path(__file__).resolve().parents[1]
DOCS = REPO / "docs"
BANNER = (
    "> **All data behind this document is synthetic and the system is not validated on real data.**\n"
    "> Simulated money, sandbox prototype, not a product of upay or any other company.\n"
    "> Generated by `scripts/build_docs.py` from `reports/*.json`; do not edit by hand.\n"
)
NOT_MEASURED = "not measured"


def load(name: str) -> dict[str, Any] | None:
    path = REPO / "reports" / name
    return json.loads(path.read_text(encoding="utf-8")) if path.exists() else None


def pct(value: float | None, digits: int = 1) -> str:
    return NOT_MEASURED if value is None else f"{value * 100:.{digits}f}%"


def num(value: float | None, digits: int = 3) -> str:
    return NOT_MEASURED if value is None else f"{value:.{digits}f}"


def get(node: Any, *path: str) -> Any:
    for key in path:
        if not isinstance(node, dict) or key not in node:
            return None
        node = node[key]
    return node


def plain(counts: dict[str, Any]) -> str:
    return ", ".join(f"{k}: {v}" for k, v in counts.items())


def table(head: list[str], rows: list[list[str]]) -> str:
    lines = ["| " + " | ".join(head) + " |", "|" + "|".join("---" for _ in head) + "|"]
    lines += ["| " + " | ".join(row) + " |" for row in rows]
    return "\n".join(lines)


# ---- model card -------------------------------------------------------------------------------


def model_card(cfg: dict[str, Any]) -> str:
    meta = json.loads((REPO / "models" / "trust_v1.meta.json").read_text(encoding="utf-8"))
    ev = load("trust_eval.json")
    if ev is None:
        raise SystemExit("reports/trust_eval.json is missing: run `make eval` first")
    noisy, clean = ev["test_v2"]["noisy_label"], ev["test_v2"]["clean_label"]
    target = ev["target_false_positive_rate"]
    policies = ev["fairness_and_policy_v2"]
    comparison = table(
        [
            "Measure (generator v2, noisy label)",
            "Trust model",
            "Account-age score",
            "Age rule (< 14 days)",
        ],
        [
            [
                "PR-AUC",
                num(noisy["model"]["pr_auc"]),
                num(noisy["age_score_baseline"]["pr_auc"]),
                "-",
            ],
            [
                "ROC-AUC",
                num(noisy["model"]["roc_auc"]),
                num(noisy["age_score_baseline"]["roc_auc"]),
                "-",
            ],
            [
                f"Recall at {pct(target, 0)} false alarms",
                pct(noisy["model"]["recall_at_target_fpr"]["recall"]),
                pct(noisy["age_score_baseline"]["recall_at_target_fpr"]["recall"]),
                pct(noisy["age_rule_baseline"]["recall"]),
            ],
            [
                "False-alarm rate at that point",
                pct(noisy["model"]["recall_at_target_fpr"]["false_positive_rate"]),
                pct(noisy["age_score_baseline"]["recall_at_target_fpr"]["false_positive_rate"]),
                pct(noisy["age_rule_baseline"]["false_positive_rate"]),
            ],
            ["Calibration error (ECE)", num(noisy["calibration"]["ece"]), "-", "-"],
        ],
    )
    fairness = table(
        [
            "Policy for sellers with little history",
            "Recall of high-risk",
            "Precision of HIGH_RISK band",
            "Honest new sellers wrongly HIGH_RISK",
            "Honest new sellers in LIMITED_HISTORY",
        ],
        [
            [
                f"`{key}`",
                pct(p["recall_high_risk_overall"]),
                pct(p["precision_of_high_risk_band"]),
                pct(p["false_positive_rate"]["honest_new"]),
                pct(p["limited_history_share"]["honest_new"]),
            ]
            for key, p in policies.items()
        ],
    )
    calibration = table(
        ["Mean predicted risk", "Observed high-risk share", "Sellers in bin"],
        [
            [num(b["mean_predicted"]), num(b["observed_rate"]), str(b["n"])]
            for b in noisy["calibration"]["bins"]
            if b["n"]
        ],
    )
    files = meta["trained_on"]["files"]
    data_rows = [
        [f"`{n}`", f"{v['rows']:,}", f"`{v['sha256'][:16]}...`"] for n, v in sorted(files.items())
    ]
    lat = ev["latency"]
    return f"""# Model card: seller trust model `{meta["version"]}`

{BANNER}
## Purpose and intended use

Gives a buyer a **score (0-100), a band and two to four plain-language reasons** (Bangla and
English) about a seller *before* the buyer pays through a Safe Order. The band is one of TRUSTED,
CAUTION, HIGH_RISK, or LIMITED_HISTORY (a neutral band for sellers with little history, so that
new does not mean scammer).

**Out of scope:** any decision about a real person or real money; deciding disputes (a human
analyst decides every dispute); use on real marketplace data without a new, real validation.

## Model

- Algorithm: LightGBM gradient-boosted trees, probability calibrated with {meta["calibration"]} scaling.
- {len(meta["feature_columns"])} seller features: {", ".join(f"`{c}`" for c in meta["feature_columns"])}.
- Monotone constraints: more refunds or disputes can never make a seller look safer
  ({", ".join(f"`{c}`" for c in meta["monotone_increasing_risk"])}); see "Limitations".
- Hyperparameters: {", ".join(f"`{k}={v}`" for k, v in sorted(meta["hyperparameters"].items()))}; best iteration
  {meta["training"]["best_iteration"]} (early stopping); seed {meta["seed"]}; trained {meta["trained_at"]}.
- Libraries: {", ".join(f"{k} {v}" for k, v in sorted(meta["libraries"].items()))}.
- Reasons come from the model's own per-feature contributions, mapped to fixed bilingual templates
  (`backend/app/i18n/reasons_*.json`). No generative model is involved.

## Training data

Synthetic generator **{meta["trained_on"]["generator"]}** (seed {meta["trained_on"]["seed"]}); see
`dataset_card_synthetic_sellers.md`. Split of generator v1: {meta["split"]["train"]:.0%} train,
{meta["split"]["validation"]:.0%} validation (early stopping), {meta["split"]["calibration"]:.0%}
calibration (rows: {meta["training"]["n_train"]} / {meta["training"]["n_validation"]} /
{meta["training"]["n_calibration"]}).

{table(["File", "Rows", "SHA-256 (start)"], data_rows)}

## Evaluation

Test data is a *different* synthetic generator (**v2**: shifted parameters, different mix, new
seed), 3,000 sellers, nothing tuned on it except as noted in `evaluation_protocol.md`. Headline
label: the dataset's `is_high_risk`, which has about 4% random label noise (realised: see the
dataset card).

{comparison}

On the easier *clean* label (diagnostic only): model PR-AUC {num(clean["model"]["pr_auc"])}, so the
headline above is the more honest number. Validation PR-AUC on the held-out part of v1:
{num(meta["training"]["validation_pr_auc"])}.

Speed: p95 {lat["p95_ms"]:.2f} ms, max {lat["max_ms"]:.2f} ms per Trust Check against a budget of
{lat["budget_ms"]} ms ({lat["samples"]} samples).

Calibration bins on v2 (noisy label):

{calibration}

## What the model relies on

Exact tree SHAP values (LightGBM `pred_contrib`) on generator v2 are in
`reports/figures/trust_feature_importance.png` (average size per feature) and
`reports/figures/trust_one_seller.png` (one seller). The model leans mostly on cash-out speed and on
how far order prices are above the category norm, which are exactly the behaviours the synthetic
generator gives the fake sellers: a reminder that it has learned our assumptions.

## Fairness check (honest new sellers)

The blueprint hides every account younger than 14 days behind LIMITED_HISTORY. In the generated
data every `fake_burst` seller is that young: under the literal rule their recall is
{pct(policies["blueprint_literal"]["recall_by_archetype"]["fake_burst"], 0)} and overall recall of
high-risk sellers falls to {pct(policies["blueprint_literal"]["recall_high_risk_overall"])}. The configured policy
(`override_default`) still shows a limited-history seller as HIGH_RISK when its model score is
{cfg["rules"]["trust"]["limited_history_override_max_score"]} or lower.

{fairness}

Honest established sellers wrongly flagged on v2: {pct(policies["override_default"]["false_positive_rate"]["honest_established"])};
honest new sellers: {pct(policies["override_default"]["false_positive_rate"]["honest_new"])}.
**The override threshold is a policy choice that needs a human decision; it is not a finding.**

## Limitations

- **Synthetic data, not validated on real data.** The behaviour types and their parameters are
  assumptions. The model learned the generator, and the high scores above say nothing about real
  sellers. Real fraud adapts; this data does not.
- Calibration (Platt scaling on {meta["training"]["n_calibration"]} rows) is checked in the table
  above; bins with few sellers give noisy observed rates (figure: `reports/figures/calibration.png`).
- A single refund barely moves the score of a long-established seller (it moves visibly only for
  sellers with a short record), which is correct for the model but surprising in a demo.
- The monotone constraints were added after a behavioural check showed that one extra refund raised
  the score of a quarter of the sellers on v2; the measured numbers before and after are in
  `DECISIONS.md`.
- No fairness analysis by region, gender, or any real demographic is possible: the data has none.
"""


# ---- dataset card -----------------------------------------------------------------------------


def dataset_card() -> str:
    s1, s2 = load("synthetic_summary_v1.json"), load("synthetic_summary_v2.json")
    if s1 is None or s2 is None:
        raise SystemExit("reports/synthetic_summary_v*.json are missing: run `make data` first")
    gen = load_config()["generator"]
    rows = []
    for name in sorted(s1["per_archetype"]):
        a, b = s1["per_archetype"][name], s2["per_archetype"][name]
        rows.append(
            [
                name,
                pct(a["share"], 0),
                pct(b["share"], 0),
                f"{a['age']:.0f} / {b['age']:.0f}",
                f"{a['unique_buyers_24h']:.1f} / {b['unique_buyers_24h']:.1f}",
                f"{a['refund_rate']:.3f} / {b['refund_rate']:.3f}",
            ]
        )
    return f"""# Dataset card: synthetic seller data (generator v1 and v2)

{BANNER}
## What it is

Sellers, buyers, orders and daily statistics produced by `scripts/generate_sellers.py` from the
parameters in `config/config.yaml`. Names are "Synthetic Shop NNNN", wallet numbers start with
`SIM-W-`. **There is no real person, seller, wallet or transaction in it.** Every parameter is an
assumption, listed in full in `synthetic_assumptions.md`.

| | v1 (training) | v2 (test) |
|---|---|---|
| Seed | {gen["seeds"]["v1"]} | {gen["seeds"]["v2"]} |
| Sellers | {s1["n_sellers"]:,} | {s2["n_sellers"]:,} |
| Orders | {s1["n_orders"]:,} | {s2["n_orders"]:,} |
| Share labelled high-risk (`is_high_risk`) | {pct(s1["high_risk_share"])} | {pct(s2["high_risk_share"])} |
| Label noise realised | {pct(s1["label_noise_realised"])} | {pct(s2["label_noise_realised"])} |

v2 shifts the archetype parameters by about +/-20% and uses a different archetype mix, so a model
that memorised v1 loses points on v2.

## Hidden behaviour types (ground truth, never shown in the app)

{table(["Archetype", "Share v1", "Share v2", "Mean account age days (v1 / v2)", "Mean buyers in 24 h (v1 / v2)", "Mean refund rate (v1 / v2)"], rows)}

## Labels

`is_high_risk` is 1 for the three fraud archetypes (`fake_burst`, `slow_scammer`,
`collusive_ring`) with a random flip of about {gen["label_noise"]:.0%}. `chronic_poor_service`
sellers are deliberately **not** labelled high-risk: poor service is not fraud.

## Known limitations

- It encodes our own assumptions about how fake sellers behave; the model is graded on whether it
  finds them again. That is a test of the pipeline, not of reality.
- The fraud archetypes are cleanly separable by design, apart from the label noise and an
  intentional overlap with honest new sellers. Real data would be messier.
- No language, region or demographic attributes exist, so no demographic fairness check is possible.
- Daily statistics cover {gen["stats_window_days"][0]}-{gen["stats_window_days"][1]} days before
  {gen["as_of"][:10]}.

## Dispute cases

The dataset of written dispute cases (for the dispute classifier) **does not exist yet**: the
team's case files (BLUEPRINT.md Step 5) have not been added to `raw/`. A card for it will be
generated once it exists. Until then no dispute-classifier number appears anywhere.
"""


# ---- dispute classifier documents -------------------------------------------------------------


def dispute_model_card(cfg: dict[str, Any]) -> str:
    report = load("dispute_eval_baseline.json")
    meta_path = REPO / "models" / "dispute_baseline_v1.meta.json"
    if report is None or not meta_path.exists():
        raise SystemExit("dispute report/model missing: run `make cases train-dispute eval` first")
    meta = json.loads(meta_path.read_text(encoding="utf-8"))
    splits, routing, inj = report["splits"], report["routing"], report["injection"]
    rows = []
    for name in ("validation", "test1", "test2"):
        s = splits[name]
        rows.append(
            [
                name,
                str(s["n"]),
                str(s["distinct_stories"]),
                num(s["macro_f1"]),
                pct(s["accuracy"]),
                pct(s["wrong_refund_rate"]),
                pct(s["wrong_rejection_rate"]),
                num(s["calibration_ece"]),
                num(s["story_level"]["macro_f1"]),
            ]
        )
    summary = table(
        [
            "Split",
            "Cases",
            "Distinct stories",
            "Macro-F1",
            "Accuracy",
            "Wrong-refund rate",
            "Wrong-rejection rate",
            "ECE",
            "Macro-F1 (one case per story)",
        ],
        rows,
    )
    classes = list(splits["test1"]["per_class"])
    per_class = table(
        [
            "Class",
            "Precision (test 1)",
            "Recall (test 1)",
            "F1 (test 1)",
            "Precision (test 2)",
            "Recall (test 2)",
            "F1 (test 2)",
        ],
        [
            [
                c,
                *[
                    num(splits[s]["per_class"][c][k], 2)
                    for s in ("test1", "test2")
                    for k in ("precision", "recall", "f1")
                ],
            ]
            for c in classes
        ],
    )
    route_rows = [
        [
            name,
            pct(r["fast_lane_share"]),
            pct(r["fast_lane_accuracy"]),
            str(r["fast_lane_wrong_refunds"]),
            pct(r["human_review_share"]),
        ]
        for name, r in routing.items()
    ]
    routes = table(
        [
            "Split",
            "Sent to fast lane",
            "Fast-lane accuracy",
            "Fast-lane wrong refunds",
            "Sent to a human",
        ],
        route_rows,
    )
    lat = report["latency"]
    return f"""# Model card: dispute classifier `{meta["version"]}`

{BANNER}
## Purpose and intended use

Reads one dispute (courier status, whether the delivery code was used, an amount band, and four
short texts: the buyer's claim, the seller's response, each side's evidence description) and gives
**probabilities for four classes**: SELLER_FAULT, BUYER_FALSE_CLAIM, COURIER_ISSUE and
INSUFFICIENT_EVIDENCE. The evidence analyzer turns them into a *suggestion* for a human analyst
and a route (fast lane or human review). **It never decides and never moves money.**

**Out of scope:** deciding disputes, any use on real people, real money or real disputes without a
new validation on governed data.

## Model

- TF-IDF (word 1-2 grams and character 2-5 grams) + class-balanced logistic regression, sigmoid
  calibration fitted on the validation split. No generative model, no embeddings.
- Hyperparameters: {", ".join(f"`{k}={v}`" for k, v in sorted(meta["hyperparameters"].items()))}.
- Input text: `[COURIER=..] [CODE=..] [AMOUNT_BAND=..] BUYER: .. SELLER: .. BUYER_EVIDENCE: .. SELLER_EVIDENCE: ..`
  (`backend/app/disputes/text_format.py`). Instruction-like sentences are removed first by the
  injection screen (see the responsible-AI note for how far that goes).
- Libraries: {", ".join(f"{k} {v}" for k, v in sorted(meta["libraries"].items()))}; trained {meta["trained_at"]}.
- Speed: p95 {lat["p95_ms"]:.1f} ms, max {lat["max_ms"]:.1f} ms per prediction (budget {lat["budget_ms"]} ms).

## Training data

See `dataset_card_dispute_cases.md`. Train: {meta["trained_on"]["train"]["rows"]} cases; validation
(calibration): {meta["trained_on"]["validation"]["rows"]} cases. **All cases were written by the AI
assistant that built this repository, not by ChatGPT, Gemini or the team.**

## Evaluation (read this before quoting any number)

{summary}

- **One author for every split.** Train, validation, Test 1 and Test 2 were all written by the same
  assistant. The splits guarantee that no claim text and no combination of source texts used in a
  test appears in training, so the numbers show how the model handles wording it has not seen. They do
  **not** show how it handles cases written by other people, other styles or real disputes, and
  they are likely to be optimistic for that purpose.
- **Few distinct stories in the test sets.** The test texts are drawn from a small held-out pool,
  so many cases repeat the same story with different product names and amounts: see "Distinct
  stories" and the last column, which scores one case per story.
- Validation was used to fit the calibration, so its row is not an honest test.
- Nothing was tuned on Test 1 or Test 2.
- Definitions: *wrong-refund rate* = share of true BUYER_FALSE_CLAIM cases predicted SELLER_FAULT or
  COURIER_ISSUE (a refund would be suggested); *wrong-rejection rate* = share of true SELLER_FAULT
  or COURIER_ISSUE cases predicted BUYER_FALSE_CLAIM (a rejection would be suggested). These errors
  matter because a human analyst has to catch them.

Per class:

{per_class}

## Routing through the full analyzer

The analyzer applies rules to the probabilities, the flags and the amount. A case goes to the fast
lane only if the model is confident, the amount is low, no flag fired and no injection was found;
the fast lane still needs a human click. The case records carry no dispute history, so
REPEAT_CLAIMANT never fires here.

{routes}

## Prompt injection

{inj["screen_detected"]} of {inj["n"]} injected cases had their instruction sentence detected by the
screen. Compared with its twin (the same case without the sentence), the recommendation changed in
{inj["pipeline_recommendation_changed"]} cases; {inj["human_review_forced"]} of {inj["n"]} were
sent to a human. A sentence the screen misses reaches the model as ordinary words, and can move a
bag-of-words model only through those words. Details: `reports/dispute_eval_baseline.json`.

## Limitations

- Synthetic, single-author data; not validated on real data; real disputes are messier, longer and
  use other words (and the Bangla, especially the "regional" style, needs native review).
- The test sets hold few distinct stories (see above), so the numbers have wide uncertainty.
- INSUFFICIENT_EVIDENCE is the hardest class (see the confusion matrix in
  `reports/figures/dispute_confusion_test1.png`): the model often mixes it with the faults, which
  is why low confidence goes to a human.
- Evidence is text only: there is no image or video analysis.
"""


def dispute_dataset_card(cfg: dict[str, Any]) -> str:
    stats, splits = load("dispute_cases_stats.json"), load("dispute_cases_splits.json")
    if stats is None or splits is None:
        raise SystemExit("case reports missing: run `make cases` first")
    rows = []
    for name, info in splits["splits"].items():
        rows.append(
            [
                name,
                str(info["n"]),
                str(info["batches"]),
                str(info["distinct_stories"]),
                ", ".join(f"{k}: {v}" for k, v in info["by_source"].items()),
            ]
        )
    return f"""# Dataset card: dispute cases

{BANNER}
## Source, stated plainly

**Every case was written by the AI assistant that built this repository** from the bank in
`scripts/case_bank/` and combined with seeded random choices by `scripts/make_cases.py`. The cases were
**not** generated by ChatGPT or Gemini and **not** written by the team; no real person's text, chat,
name, phone number or brand was used. Provenance for every file is in `raw/PROVENANCE.md`. The
blueprint's cross-source design (ChatGPT trains, Gemini tests, team-written cases are the cleanest
test) is therefore **not** reproduced: all splits share one author.

Files from other sources (`chatgpt`, `gemini`, `team`) can be added to `raw/`; `dispute.cases.roles`
in `config/config.yaml` says which split each source fills, and the evaluation reports them per source.

## Content

Four labels with four sub-types each (BLUEPRINT.md Section 8.3), Bangla in four styles (standard,
Banglish, regional, mixed), eight product categories, amounts in taka, courier status and whether
the delivery code was used. {stats["kept"]} cases kept out of {stats["read"]} read; dropped:
{plain(stats["dropped"]) or "none"} (the dropped ones are repeated text combinations).

Per label: {plain(stats["by_label"])}.
Per language style: {plain(stats["by_language_style"])}.
Per sub-type: {plain(stats["by_subtype"])}.

## Splits

{table(["Split", "Cases", "Batches", "Distinct stories", "Sources"], rows)}

- Split by source and batch, never by random row. A test claim text never appears in training (the
  split script removes shared claims and fails if any remain) and no combination of source texts is
  shared between splits (`story_key`). The injection set holds test-style cases with an added
  instruction sentence; it is never trained on and shares no claim text with train or validation.
- **A distinct story is one combination of a claim wording and the three other texts.** The
  held-out pools are small, so test sets repeat stories with different product names and amounts:
  the number of distinct stories is far smaller than the number of cases (table above).
- Cases are made realistic with ambiguity on purpose: the same "I did not receive it" wording is
  used by sellers' faults, false claims, courier problems and unclear cases, so the other fields
  must decide. About 10% of seller responses or evidence texts are blank.

## Review

**No human has reviewed these cases.** The blueprint asks the team to read about 10% and delete wrong
or unrealistic ones and to record the share deleted: this has not happened (`manual_review.done =
false` in `reports/dispute_cases_stats.json`). The Bangla, especially the regional style, was
written by an AI and needs a native speaker's review.

## Known limitations

- One author, so the dataset has one voice; real users write differently, and longer.
- The texts follow templates written for each sub-type: a model can learn the templates.
- Not validated on real data; no real disputes were used.
- Using the assistant's own writing as training data for a model: the licence register lists the
  terms question to confirm.
"""


# ---- evaluation protocol ----------------------------------------------------------------------


def evaluation_protocol(cfg: dict[str, Any]) -> str:
    split = cfg["trust_model"]["split"]
    ev = load("trust_eval.json")
    inj = load("injection_eval.json")
    inj_text = ""
    if inj:
        inj_text = f"""
## Injection checks

- Phrases the screen was built on: {inj["screen"]["detected"]} of {inj["screen"]["injection_phrases"]}
  detected. This is a **regression check only**: the patterns were written while looking at them.
- Phrases written after the screen and never used to change it:
  {inj["untuned_screen"]["detected"]} of {inj["untuned_screen"]["phrases"]} detected. Developer-written
  and small, an indication only.
- False alarms on ordinary complaints: {inj["screen"]["false_alarms"]} of {inj["screen"]["harmless_phrases"]}.
- Invariance: {inj["invariance"]["pairs_checked"]} pairs (injected vs plain evidence, stand-in
  classifier): the classifier text, probabilities, recommendation and other flags never changed and
  human review was always forced. This holds by construction with a stand-in and says nothing about
  a trained classifier.
- The team's held-out injection set: {NOT_MEASURED} (not available yet).
"""
    return f"""# Evaluation protocol

{BANNER}
## Seller trust model

1. **Training data:** synthetic generator v1 only. **Splits** (stratified by label, seed
   {cfg["trust_model"]["seed"]}): {split["train"]:.0%} train, {split["validation"]:.0%} validation
   (early stopping only), {split["calibration"]:.0%} calibration (Platt scaling only).
2. **Test data:** generator v2: a different seed, parameters shifted by about +/-20% and a
   different archetype mix. No v2 row was used to fit, stop or calibrate the model.
3. **What did look at v2, in full disclosure:** the limited-history override threshold
   ({cfg["rules"]["trust"]["limited_history_override_max_score"]}) was fixed before looking at v2
   results, but the three-policy comparison that documents the blueprint conflict is measured on v2; and the monotone
   constraints on `refund_rate` and `dispute_rate` were added after a behavioural check on v2 sellers.
   Accuracy was compared before and after and did not drop (`DECISIONS.md`), but strictly v2 has
   influenced the way the design was decided, so it is a held-out *generator*, not a pristine blind test.
4. **Labels:** headline = `is_high_risk` (about 4% random noise); the clean archetype label is a
   diagnostic only.
5. **Metrics:** PR-AUC and ROC-AUC (ranking); recall at a fixed false-alarm rate of
   {cfg["trust_model"]["eval"]["target_fpr"]:.0%} (the number a product owner cares about, because
   the classes are imbalanced and accuracy would mislead); expected calibration error with
   {cfg["trust_model"]["eval"]["calibration_bins"]} bins; per-cohort false-positive rates for
   honest established, honest new and chronic-poor-service sellers.
6. **Baselines:** the account-age score (ranking by newness) and the simple age rule
   (< {cfg["rules"]["trust"]["limited_history_max_age_days"]} days = high risk).
7. **Speed:** {cfg["trust_model"]["eval"]["latency_samples"]} timed predictions against a
   {cfg["trust_model"]["latency_budget_ms"]} ms budget.
8. **Leakage checks:** the ground-truth archetype and `ring_id` are not model inputs (the feature
   list is fixed in `backend/app/trust/features.py`); features are computed only from orders before
   the scoring moment (tested).

## Dispute classifier and routing

1. **Data:** assistant-written cases (see the dataset card); every split has the same author.
2. **Splits:** by source and batch. Train = `ai_a` batches; validation = its `_val` batches
   (used only to fit the probability calibration); Test 1 = `ai_b`; Test 2 = `ai_c`; the
   injection set = `ai_inj`. Cases from `chatgpt`, `gemini` and `team` sources would fill the same
   roles (`dispute.cases.roles`). A claim text or a story (combination of source texts) never appears
   in two of train, validation, Test 1 and Test 2; the split script enforces it and tests check it.
3. **No tuning on test:** the hyperparameters in the config were set once, before the first
   evaluation, and not changed afterwards. Calibration (sigmoid) was chosen by the specification, and
   the uncalibrated model is not used.
4. **Metrics:** macro-F1 and accuracy; per-class precision, recall and F1; confusion matrices;
   the wrong-refund and wrong-rejection rates (definitions in the model card); top-label calibration
   error and log-loss; each of these per source and per language style; and again on one case per
   distinct story, because the held-out pools are small and the same story repeats.
5. **Routing:** every test case is run through the real analyzer; the report gives the fast-lane
   share, its accuracy and its wrong refunds, and the reasons for human review.
6. **Injection:** each injected case is compared with its twin (same case without the sentence).
7. **Speed:** 300 timed predictions against a 100 ms budget.
8. **What this cannot tell:** how the model does on text written by other people or on real
   disputes. That needs the team's own cases (source `team`) and, in the end, governed real data.

{inj_text}
## Analyst time study

{NOT_MEASURED}: no timed sessions yet. If run, it is a small unblinded team study and is reported as
an indication only.

## Reproduce

`make data && make train && make eval && make docs`. The numbers in this document come from
`reports/*.json`; the sources are hashed in `reports/summary.json`.{"" if ev else " (trust report missing)"}
"""


# ---- responsible AI ---------------------------------------------------------------------------


def responsible_ai(cfg: dict[str, Any]) -> str:
    ev = load("trust_eval.json")
    inj = load("injection_eval.json")
    policies = get(ev, "fairness_and_policy_v2") or {}
    literal = get(policies, "blueprint_literal", "recall_high_risk_overall")
    override = get(policies, "override_default", "recall_high_risk_overall")
    untuned = get(inj, "untuned_screen")
    dispute = load("dispute_eval_baseline.json")
    dispute_line = (
        f" On held-out cases written by the same assistant that wrote the training cases, "
        f"the dispute classifier would suggest a refund for {pct(get(dispute, 'splits', 'test1', 'wrong_refund_rate'))} "
        f"(test 1) and {pct(get(dispute, 'splits', 'test2', 'wrong_refund_rate'))} (test 2) of false "
        "claims, which is exactly why a person checks every case. These numbers come from one author "
        "and say little about real disputes."
        if dispute
        else ""
    )
    injection_line = (
        f"The pattern screen caught {untuned['detected']} of {untuned['phrases']} injection phrases "
        "written after it was built (and all of those it was built on): it is a first filter, "
        "not a defence."
        if untuned
        else f"Injection screen results: {NOT_MEASURED}."
    )
    return f"""# Responsible AI note

{BANNER}
**Privacy.** The prototype holds no personal data: names are generated, wallet numbers carry a
`SIM-` prefix, money is simulated. Only the minimum a dispute needs is stored (claim text,
evidence text, timestamps). Hidden fields (ground-truth archetype, internal scores of limited-history
sellers) are excluded from API responses (tested). Evidence text is shown escaped. There is no
sign-in in the sandbox; a real deployment would need authentication, access control and a data
protection review that this prototype does not provide.

**Explainability.** Every Trust Check shows two to four reasons and every analyst case shows a
timeline, flags, class probabilities and a written explanation built from fixed bilingual
templates. No generative model is anywhere in the decision path.

**Fairness.** New sellers are not scammers. Sellers with little history get a neutral
LIMITED_HISTORY band instead of a score. Literally applying the blueprint rule hides the high-risk
fakes too (recall of high-risk sellers {pct(literal)} on the test data); the configured policy keeps
them visible (recall {pct(override)}) while honest new sellers wrongly flagged are
{pct(get(policies, "override_default", "false_positive_rate", "honest_new"))}. That threshold is a
policy choice for humans to confirm. No demographic fairness check is possible with synthetic data.

**Security.** Dispute text is untrusted input. A screen removes instruction-like sentences before
the classifier and rules see them and forces human review when one is found. {injection_line}
The real protection is structural: no free text can change a label, a route or a ledger entry, the
ledger is double-entry and append-only (database triggers), and every state change is audited.
Inputs have length limits and are validated.

**Human oversight.** The analyzer only *suggests*. A person decides every dispute, must write a
note, and confirms any money movement. Low confidence, high amounts, any flag, or insufficient
evidence send a case to a human; the fast lane only pre-fills a confirm button and is never automatic.{dispute_line}
Seller trust scores update only after a human decision.

**Limits to state out loud.** Everything is synthetic and not validated on real data; the Bangla
text was drafted by an AI assistant and needs review by a native speaker; holding customer funds
may need regulatory approval, so Safe Order is shown as a future feature governed by the payment
provider, simulated here.
"""


# ---- licence register -------------------------------------------------------------------------

SKIP_LINE = 80


def python_licence(name: str) -> tuple[str, str]:
    try:
        meta = metadata.metadata(name)
    except metadata.PackageNotFoundError:
        return "not installed", "-"
    version = meta.get("Version", "?")
    expression = meta.get("License-Expression")
    if expression:
        return version, expression
    classifiers = [
        c.split("::")[-1].strip()
        for c in meta.get_all("Classifier", [])
        if c.startswith("License ::")
    ]
    if classifiers:
        return version, "; ".join(classifiers)
    text = (meta.get("License") or "").strip().splitlines()
    if text and len(text[0]) <= SKIP_LINE:
        return version, text[0]
    return version, "see package metadata (not summarised by the script)"


def licence_register() -> str:
    requirements = [
        line.strip()
        for line in (REPO / "requirements.txt").read_text().splitlines()
        if line.strip()
    ]
    py_rows = [[f"`{n}`", *python_licence(n)] for n in requirements]
    package = json.loads((REPO / "frontend" / "package.json").read_text(encoding="utf-8"))
    js_rows = []
    for section in ("dependencies", "devDependencies"):
        for name, wanted in sorted(package[section].items()):
            installed = REPO / "frontend" / "node_modules" / name / "package.json"
            if installed.exists():
                info = json.loads(installed.read_text(encoding="utf-8"))
                licence = info.get("license")
                if isinstance(licence, dict):
                    licence = licence.get("type")
                js_rows.append(
                    [
                        f"`{name}`",
                        info.get("version", wanted),
                        str(licence or "not stated"),
                        section,
                    ]
                )
            else:
                js_rows.append([f"`{name}`", wanted, "not installed here", section])
    return f"""# Licence register

{BANNER}
Python and JavaScript licences below are read from the installed package metadata by the script, so
they are what is installed *here*, not a legal opinion. Items a script cannot know are marked
"to confirm". Nothing here is legal advice: have the team (and, for any product use, a lawyer) check
the obligations.

## Python packages (`requirements.txt`)

{table(["Package", "Installed version", "Licence (from metadata)"], py_rows)}

## Frontend packages (`frontend/package.json`)

{table(["Package", "Version", "Licence (from metadata)", "Kind"], js_rows)}

## Models, datasets and other assets

| Item | Use | Licence / status |
|---|---|---|
| Base language models | none used so far | The optional transformer (Step 13) is not started. Some Bangla models are non-commercial: check before use. |
| Public datasets | none used | none |
| Synthetic seller data | generated by our own script | ours (the team decides); contains nothing real |
| Dispute case files | written by the AI assistant (`raw/PROVENANCE.md`) | ours to decide; whether the assistant's terms allow training even a small classifier on its output is **to confirm** (see below) |
| Noto Sans Bengali font | loaded from Google Fonts in the browser | to confirm; the sandbox falls back to system fonts if blocked |
| Kaggle private dataset and notebook | storage and demo copy | private; Kaggle's terms apply |

## Open questions that a human must settle

- **LLM terms of use:** whether the current terms of the tool that wrote the cases (the AI
  assistant here; ChatGPT or Gemini if the team adds their cases) allow using its output to train
  another model, even a small TF-IDF classifier. Not checked. A person must read the terms and record
  the conclusion.
- **Our own licence:** the repository has no licence file yet; until the team and any organiser
  rules decide, all rights are reserved by default.
"""


def index(done: dict[str, bool]) -> str:
    rows = [
        ["Model card (trust model)", "`model_card_trust.md`", "generated"],
        ["Dataset card (synthetic sellers)", "`dataset_card_synthetic_sellers.md`", "generated"],
        ["Synthetic data assumptions", "`synthetic_assumptions.md`", "generated by `make data`"],
        ["Evaluation protocol", "`evaluation_protocol.md`", "generated"],
        ["Responsible AI note", "`responsible_ai.md`", "generated"],
        ["Licence register", "`licence_register.md`", "generated; open questions listed inside"],
        ["Model card (dispute classifier)", "`model_card_dispute_classifier.md`", "generated"],
        [
            "Dataset card (dispute cases)",
            "`dataset_card_dispute_cases.md`",
            "generated; the cases are assistant-written and unreviewed",
        ],
        ["API contract", "`openapi.json`", "generated by `make openapi`"],
        ["Time study template", "`time_study_template.json`", "template; the team fills it in"],
        [
            "Team agreement, logic chain, interview consent, safe-order terms draft, regulatory note, "
            "organiser questions, prompt log",
            "-",
            "human documents: not written by this code",
        ],
    ]
    return f"""# Documentation index

{BANNER}
{table(["Document", "File", "Status"], rows)}

Regenerate with `make eval && make docs`.
"""


def main() -> None:
    cfg = load_config()
    outputs = {
        "model_card_trust.md": model_card(cfg),
        "dataset_card_synthetic_sellers.md": dataset_card(),
        "evaluation_protocol.md": evaluation_protocol(cfg),
        "responsible_ai.md": responsible_ai(cfg),
        "model_card_dispute_classifier.md": dispute_model_card(cfg),
        "dataset_card_dispute_cases.md": dispute_dataset_card(cfg),
        "licence_register.md": licence_register(),
    }
    for name, text in outputs.items():
        (DOCS / name).write_text(text, encoding="utf-8")
        print(f"wrote docs/{name}")
    (DOCS / "README.md").write_text(index({}), encoding="utf-8")
    print("wrote docs/README.md")


if __name__ == "__main__":
    main()
