"""Package every trained model for the PRIVATE Kaggle dataset "safeorder-trained-models".

Usage (repository root):
  PYTHONPATH=backend:. python -m scripts.publish_models_kaggle          # build the folder
  PYTHONPATH=backend:. python -m scripts.publish_models_kaggle --push   # build, then upload

The folder holds what a reviewer needs to see where each model came from: the model files in
``models/`` (joblib, ``*.meta.json`` and any fine-tuned model folder), the evaluation reports in
``reports/``, and ``MODELS.md``, an index generated from those files (sizes, SHA-256, and values
read from each ``*.meta.json``). Nothing is typed in by hand, so no number can drift from the
files. Raw dispute case files and generated synthetic data are never included.
"""

import argparse
import hashlib
import json
import shutil
import subprocess
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
OUT = REPO / "build" / "kaggle" / "models"
OWNER = "bmr07sakaria"
DATASET_SLUG = "safeorder-trained-models"
REPORT_PATTERNS = ("*eval*.json", "summary.json", "figures/*.png")
MODEL_SUFFIXES = {".joblib", ".json", ".pt", ".pkl", ".bin", ".safetensors", ".txt", ".md"}
META_KEYS = ("version", "trained_on", "calibration", "training", "licence", "base_model")


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1 << 20), b""):
            digest.update(block)
    return digest.hexdigest()


def collect_models() -> list[Path]:
    models = REPO / "models"
    if not models.exists():
        raise SystemExit("models/ is missing: run `make train` first")
    files = [
        p for p in sorted(models.rglob("*"))
        if p.is_file() and p.suffix in MODEL_SUFFIXES
    ]  # fmt: skip
    if not files:
        raise SystemExit("models/ holds no model files: run `make train` first")
    return files


def collect_reports() -> list[Path]:
    reports = REPO / "reports"
    found: list[Path] = []
    for pattern in REPORT_PATTERNS:
        found += sorted(reports.glob(pattern))
    return sorted(set(found))


def describe(path: Path) -> str:
    rel = path.relative_to(REPO)
    size_kb = path.stat().st_size / 1024
    return f"- `{rel}` ({size_kb:,.1f} KB, sha256 `{sha256(path)[:16]}...`)"


def meta_section(meta_path: Path) -> list[str]:
    meta = json.loads(meta_path.read_text(encoding="utf-8"))
    lines = [f"### {meta_path.name}", ""]
    for key in META_KEYS:
        if key in meta:
            lines.append(f"- {key}: `{json.dumps(meta[key], ensure_ascii=False)}`")
    return lines + [""]


def build() -> Path:
    if OUT.exists():
        shutil.rmtree(OUT)
    OUT.mkdir(parents=True)
    models, reports = collect_models(), collect_reports()
    reports += sorted((REPO / "docs").glob("model_card*.md"))  # the cards travel with the models
    for path in models + reports:
        target = OUT / path.relative_to(REPO)
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy(path, target)

    lines = [
        "# SafeOrder trained models (private)",
        "",
        "Generated by `scripts/publish_models_kaggle.py` from the repository's `models/` and",
        "`reports/` folders. Every model here was trained on **synthetic or team-written data**",
        "and is **not validated on real data**. Simulated money; not a product of any company.",
        "",
        "## Files",
        "",
        *[describe(p) for p in models + reports],
        "",
        "## Model metadata (read from the `*.meta.json` files)",
        "",
    ]
    for meta in (p for p in models if p.name.endswith(".meta.json")):
        lines += meta_section(meta)
    (OUT / "MODELS.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    (OUT / "dataset-metadata.json").write_text(
        json.dumps(
            {
                "title": "SafeOrder trained models",
                "id": f"{OWNER}/{DATASET_SLUG}",
                "subtitle": "Trained SafeOrder models and their evaluation reports (private)",
                "description": "\n".join(lines),
                "licenses": [{"name": "other"}],
            },
            indent=2,
        )
        + "\n"
    )
    return OUT


def push(folder: Path) -> None:
    """New version if the dataset exists on Kaggle, otherwise create it (always private)."""
    version = [
        "kaggle",
        "datasets",
        "version",
        "-p",
        str(folder),
        "-m",
        "update trained models",
        "--dir-mode",
        "zip",
    ]
    result = subprocess.run(version, capture_output=True, text=True)
    print((result.stdout + result.stderr).strip())
    if result.returncode != 0:
        print("no existing dataset, creating it (private)")
        subprocess.run(
            ["kaggle", "datasets", "create", "-p", str(folder), "--dir-mode", "zip"], check=True
        )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--push", action="store_true", help="upload with the kaggle CLI")
    args = parser.parse_args()
    folder = build()
    print(f"built {folder}")
    if args.push:
        push(folder)


if __name__ == "__main__":
    main()
